### ISSUE TITLE
Discussion: Node.JS Slack channel

### ISSUE THREAD

**Issue by rxmarbles** [nodejs/package-maintenance#118]
I would like to raise a discussion around continued conversations beyond the meetings. As well all know with meetings it is definitely a time crunch around topics on the agenda and trying to get everyones opinion/idea. Sometimes those topics need additional time to talk through and sort out. With this in mind I would like to propose creating a channel in the official Node.JS slack room. This will allow us to continue discussions effectively and with those we are working with on particular topics that we've taken up. The one thing I would appreciate is that if we do create the channel that we be mindful of the use of `@here` and `@channel` unless absolutely necessary and that if you are responding to a user to keep it threaded. This will allow conversations to stay on point and not get lost in translation.

**Comment by ljharb** [comment]
That’s normal slack etiquette anyways.

I’ve created `#package-maintenance` on the node slack, if we decide to use that.

**Comment by rkmarks** [comment]
True, I figured I would just set a reminder of it @ljharb ;)

**Comment by wesleytodd** [comment]
Anyone with info on that slack?  I tried multiple times to use [the link to register](http://www.nodeslackers.com/) and never received an email.

**Comment by wentout** [comment]
> Anyone with info on that slack? I tried multiple times to use [the link to register](http://www.nodeslackers.com/) and never received an email.

I used it for the other groups, so I made acc before. It might you can try to make acc on website before trying to join through mentioned link.

**Comment by wesleytodd** [comment]
Ahh, I assumed that it was just an automated process.  You probably see three or so entries from me, preferably just the first one is used. Sorry :)

**Comment by frank-dspeed** [comment]
we should simply use https://gitter.im its well for this and more easy to manage

**Comment by wentout** [comment]
> we should simply use https://gitter.im its well for this and more easy to manage

Seems Slack is a **standard** for Node.js community.

If not, may also suggest telegram group?
Telegram is very fast on my 3 y.o. smartphone.
I already did it for my mates who are also here.
;^)

**Comment by rxmarbles** [comment]
@frank-dspeed not exactly a "standard" like @wentout mentions, but the official Node.JS TSC utilizes the slack server for quick communications and notifications so keeping it in the same slack server would be optimal.

**Comment by frank-dspeed** [comment]
i don't care about that part but we should also util https://spectrum.chat as it got aquired by github it will allow us to have some form of Forum Board to publish standards for package maintance

**Comment by mhdawson** [comment]
I'm +1 for using slack.

**Comment by ljharb** [comment]
There's already a slack channel; I'm happy to register an irc channel on freenode as well if people would prefer that - but we should try to strive for one place.

**Comment by frank-dspeed** [comment]
@ljharb gitter.im is well github integrated and slack is not also gitter offers irc so if you like it raw that would be the biggest community and fastest way to reach out.

**Comment by ljharb** [comment]
I'm not aware of any way slack can't be easily integrated with github that gitter can; and in my experience slack allows much more integration with everything than gitter does. Additionally, gitter's UX is not as nice as slack's.

**Comment by frank-dspeed** [comment]
@ljharb i only wanted to point that out because there are tons of projects with many users that have a slack and a gitter channel slack gets used for team internal conversation with extra integrations and gitter for public it would take much to long to point out all the differences we can simply start with slack and see how many members we get into that if we need to reach out more we move to gitter its that simple i think.

**Comment by mhdawson** [comment]
Sounds like we have consensus to start with Slack and then adjust/extend if we find we need to.  We should just add a link (and associated wording including how to register since that is a different link) for the Slack channel to the README.md and then mention in the next meeting as well.

**Comment by mhdawson** [comment]
As a side note I am trying to work with the admins of the node-js.slack to improve the registration process to make it less confusing and more consistent.

**Comment by mhdawson** [comment]
closing as we gave rest of members FYI in meeting today.
