### ISSUE TITLE
Suggestion: Priority list of issues to be solved based on severity, popularity and reported need

### ISSUE THREAD

**Issue by reinaldorauch** [nodejs/package-maintenance#14]
It may be a specific case of #5  and #4 but here goes:

A common priority list that shows issues that need to be solved to keep the package updated with the lastest version of node, based on severity, popularity of the package, and reported need by the community.

Example: I identified a compatibility issue in [nativescript-cli](https://github.com/NativeScript/nativescript-cli) that crashed it when running in node 11.0.0 that was caused by a deep dependency that was stale and not receiving updates. It would be great if that compatibility break issue showed up in a centralized list in node.js ecosystem letting more people know that issue or package needs attention to not block the package from being used in next versions of node.

PS: this is a raw thought and by no means it is a finalized idea, so I wil appreciate any suggestions on this.

**Comment by mhdawson** [comment]
I agree it would be good have a place for a list of issues that are slowing adoption for the latest version of Node.js.  We'll need to figure out what the best way to let people submit that information and then how to display it in a useful way.

**Comment by reinaldorauch** [comment]
We could use a new repo for this and digest metadata from issues from this repo to display in the page.

**Comment by Eomm** [comment]
Should also tests (or something like code coverage) a parameter of the function to define the priority?

**Comment by reinaldorauch** [comment]
@Eomm Could be, but I don't know how much of priority it has in sorting the packages.

**Comment by mcollina** [comment]
I think issues is too granular. IMHO we should focus on:

a) defining a set of criteria for modules we might want to help
b) creating and maintaining that list
c) define a process to work with the maintainer in keeping things up-to-date and stable

**Comment by mcollina** [comment]
@aoberoi I think we are in total agreement, and we are actually saying the same thing.

**Comment by mhdawson** [comment]
>therefore i think it might be better for this group to design a process for surfacing known issues to a wider audience in the community. the process should be mostly automated so that it requires the least amount of capacity as possible. i do think having a blessed repo for "ecosystem impacting issues" is one possible solution.

Is one of the approaches I had in mid for what this group might end up doing.

**Comment by reinaldorauch** [comment]
I will close this as I will not be able, unfortunately, to move forward with this
