### ISSUE TITLE
[baseline practices] Support levels

### ISSUE THREAD

**Issue by rxmarbles** [nodejs/package-maintenance#156]
This is in continuation of #119 to keep the discussion focused on one part as we can further flesh out each piece to create a draft proposal around baseline practices. 

# Support Levels
  * Support statements?
  * LTS _strategy?_
  * Refer to #5 for discussion around tooling and #139 for initial draft around support

_If I am missing anything please add a comment and tag me so I can update_

**Comment by mhdawson** [comment]
This is being covered in: https://github.com/nodejs/package-maintenance/pull/139

**Comment by rxmarbles** [comment]
closing as #139 has been merged
