### ISSUE TITLE
[baseline practices] Testing

### ISSUE THREAD

**Issue by rxmarbles** [nodejs/package-maintenance#157]
This is in continuation of #119 to keep the discussion focused on one part as we can further flesh out each piece to create a draft proposal around baseline practices. 

# Testing
  * Jest, Mocha
  * coverage should match most use cases for the module

_If I am missing anything please add a comment and tag me so I can update_

**Comment by ljharb** [comment]
Also https://npmjs.com/tape, which is the only test runner I'm aware of that works on older nodes - my typical advice is to use jest or mocha for apps, and tape for packages, since packages should be supporting as old an engine as possible (#156).

**Comment by mcollina** [comment]
I'm personally a huge fan of tap. I found that mocha tests tends to be brittle and flaky, because it runs all files within a single process. If cleanup is not done correctly, it will be really hard to prevent bad interactions between the tests.

**Comment by wesleytodd** [comment]
> Overall I do not think we should be expressing preferences here

Completely agree!  I have had the opposite experience with Mocha, it has been more stable than other runners because of its single process methodology :).  The take away from this is that we should be agnostic to technical implementation.

**Comment by rxmarbles** [comment]
agree on not expressing preferences and the proposal should focus on the available testing frameworks/methodologies.

**Comment by mhdawson** [comment]
I agree we should provide recommendations on "what" should be done, and then add information on options for "how" to do that.

**Comment by ahmadnassri** [comment]
should start with a simple context of "Why", assuming lowest level of knowledge, starting with alignment on the value of testing, why it's needed, and what benefits it provides to both the package maintainer and the users.

**Comment by craftninja** [comment]
From discussions in meeting April 22 #196 

- [ ] guidance around "how do I go from 0 to some testing"
- [ ] "there should be something in a module's package so you run `npm test` and see output, very clear whether you pass or fail"

**Comment by dominykas** [comment]
Note to self: extend both - testing and ci/cd guidelines with additional info (and link to) the "Please test in LTS" blogpost (#260).

**Comment by boneskull** [comment]
A testing guidelines doc has been merged, written by @ghinks.  Should this issue be closed?

**Comment by mhdawson** [comment]
closing
