### ISSUE TITLE
Suggestion: Provide template/guides/automation for common maintainer needs

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/package-maintenance#17]
There are many great tools and features we can take advantage of to help reduce day-to-day support workload.  All of which take time and resources to research, setup, and maintain.  That time takes away from actual support and maintenance of the modules themselves.

As an example, on Express we have talked about setting up GH issue templates, helpful bots and other things like this.  But because the main contributors prioritize the immediate need of doing security patches, responding to user support requests, reviewing PRs, and discussion of new features those things don't get done.  In a large community like Express, there are tons of repo's we would need to set this up for, making a small job for each into a big one for the whole group.

If there was a great template, guide, or even a team which could go around and do this for us, it would be super helpful.  Is there is an automated way to add this?  What about keeping them all updated as the standard changes?  I think it would be great to hear from people who have set these up and decide on the best and most impactful things we can do.

These kind of resources would save each individual maintainer group from having to go through the whole process themselves.  It would also mean that consumers and new contributors would be more likely to be familiar with the tools in use, so it might make it easier to get someone to take things over if you move on.

**Comment by bnb** [comment]
Assigned myself, per #137

**Comment by jonchurch** [comment]
This is still something we definitely want to do. We have issues floating around that relate to this, but I think this issue is too large and ambiguous to be useful as it is.

marking as `stale?` to get eyes on it before I close.

**Comment by thescientist13** [comment]
maybe this has / can been superseded by this issue now?  #373

**Comment by jonchurch** [comment]
Agreed, ty for tying it to it's successor 👍
