### ISSUE TITLE
[Team Process Documentation] Taking ideas from proposal to "implemented"

### ISSUE THREAD

**Issue by Emuentes** [nodejs/package-maintenance#191]
As we create tools, what steps do we need to make sure we follow to get the most out of our contributions.

This issue began as part of the discussion of this issue:
https://github.com/nodejs/package-maintenance/issues/161

The issue has been addressed by @Eomm by creating the tool that the issue described as proposed by @ljharb.

@ljharb suggested that we should open PRs to implement the tool in the projects that would benefit most and as use of the tool increases across the ecosystem we can consider moving it from @Eomm's repo to the Node or NPM ecosystems as desired or needed by the teams.

This thread is to discuss the above approach and any alternatives or missing pieces in our strategy for evolving our contributions from the proposal phase to an implemented solution that brings value to the community.

**Comment by Emuentes** [comment]
The first example of this process being completed & validated is here:
https://github.com/nodejs/package-maintenance/issues/192

**Comment by Emuentes** [comment]
So far the process for on-boarding a new tool appears to be:

1. Propose the tool here in the Package Maintenance Team repo by adding an issue describing your idea

2. Put your proposal on the [agenda for the next meeting](https://github.com/nodejs/package-maintenance/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+meeting+)

3. Discuss with the group during our team meeting so we can plan next steps. (See [Calendar](https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98@group.calendar.google.com) for date/time)

4. Build the tool as a public GitHub repo that follows Package Maintenance Team standards
- https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/Baseline%20practice%20-%20Document%20support%20levels.md

5. Release your tool as a public NPM module (following our [documented steps for publishing modules](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PUBLISH-GUIDELINES.md))

6. **As Needed:** Follow the steps for [transferring you repo into the org.](https://github.com/nodejs/admin/blob/0f2af76492b9efff8bafedbf650bb0a3c4f76e44/transfer-repo-into-the-org.md)

@Eomm @ljharb As folks who thumbs-upped this issue:

Do y'all feel it would be beneficial to build out a documentation section for this?
I created a PR for one as an example:
https://github.com/nodejs/package-maintenance/compare/master...Emuentes:master

I know the process wasn't particularly clear, before we gave it our first attempt, what the appropriate steps would be. I think it would bring value to have a documented example case of our process in action!

**Comment by Emuentes** [comment]
So far the process for on-boarding a new tool appears to be:

1. Propose the tool here in the Package Maintenance Team repo by adding an issue describing your idea

2. Put your proposal on the [agenda for the next meeting](https://github.com/nodejs/package-maintenance/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+meeting+)

3. Discuss with the group during our team meeting so we can plan next steps. (See [Calendar](https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98@group.calendar.google.com) for date/time)

4. Build the tool as a public GitHub repo that follows Package Maintenance Team standards
- https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/Baseline%20practice%20-%20Document%20support%20levels.md

5. Release your tool as a public NPM module (following our [documented steps for publishing modules](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PUBLISH-GUIDELINES.md))

6. **As Needed:** Follow the steps for [transferring you repo into the org.](https://github.com/nodejs/admin/blob/0f2af76492b9efff8bafedbf650bb0a3c4f76e44/transfer-repo-into-the-org.md)

@Eomm @ljharb As folks who thumbs-upped this issue:

Do y'all feel it would be beneficial to build out a documentation section for this?
I created a PR for one as an example:
https://github.com/nodejs/package-maintenance/compare/master...Emuentes:master

I know the process wasn't particularly clear, before we gave it our first attempt, what the appropriate steps would be. I think it would bring value to have a documented example case of our process in action!

**Comment by mhdawson** [comment]
PR to land merged, close.
