### ISSUE TITLE
May 6 meeting - Need chair or move?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#199]
I'm away on May 6 and I've asked those who are already setup to stream meeting but none of them can make it either.

We'll need a volunteer to chair and go without a stream or we could move to May 13.  @nodejs/package-maintenance thoughts?

**Comment by mcollina** [comment]
At what time will the meeting be on May 13th? I can be there (I’ll be in Manhattan).

**Comment by mhdawson** [comment]
It's 2-3 EST.

**Comment by mhdawson** [comment]
@mcollina ^^

**Comment by Eomm** [comment]
I can't participate in the afternoon; for me, 13th is better in order to see the YouTube stream

**Comment by craftninja** [comment]
I'll be unavailable on the 13th, but not a blocker for the meeting.

**Comment by ljharb** [comment]
I can make the 6th but am traveling on the 13th.

**Comment by ghinks** [comment]
@ghinks and @Emuentes are volunteering to chair on the 6th. I'll have to touch base with someone about the starting the live stream etc.

**Comment by dominykas** [comment]
Is this happening? Or am I on the wrong zoom or smth?

**Comment by rxmarbles** [comment]
Correct room, however not sure where the hosts are 🤔

**Comment by craftninja** [comment]
We are headed here for now https://us04web.zoom.us/j/581921842

**Comment by rxmarbles** [comment]
Due to issues w/ communication tools (zoom and no access to nodejs youtube channel for streaming) we are pushing todays meeting. to next week on the 13th. Apologize for the late communiqué and hope to see everyone next week
