### ISSUE TITLE
[tool] used-by -- find the biggest users of a package

### ISSUE THREAD

**Issue by Eomm** [nodejs/package-maintenance#214]
Based on [this documents](https://github.com/nodejs/package-maintenance/tree/master/pilots) this issue cover a bullet point from [this task list](https://github.com/nodejs/package-maintenance/blob/master/pilots/mqttjs/TASKS.md)

The topic is:

> find collaborators to refactor tests to fix CI
> - identify some companies that use MQTT.js
> - ask them to start a collaboration to let the module rise again

For this issue, I think we could:
- [brute force idea] release a version that shows a disclaimer message on the install of this package
- check the [used list](https://github.com/mqttjs/MQTT.js/network/dependents) and find companies to contact and open an issue on their repo with a disclaimer message (let's call "call to action")

I think that we must consider that our actions should be replicable for other packages, also.

**Comment by Eomm** [comment]
We are always talking about how users can support a package, but here we want to reverse the situation and let the maintainers find the users.

The idea here is to create a tool that lists the users by stars and forks (desc) looking the "used by" function in GH, so maintainer can ask support to the top 10 users.

@wesleytodd WDYT?

**Comment by mcollina** [comment]
This would be amazing actually.

**Comment by wesleytodd** [comment]
Yeah really cool idea.  I think we could look at "used by" on github, but also on the registry data.

**Comment by mhdawson** [comment]
It would be an interesting thing to explore. The tool to figure out the top users would be useful in an number of ways.  The second part of how to approach those users, what kinds of help to ask for etc. would be interesting to work through as well.

**Comment by Eomm** [comment]
The GH api to get the "used by" seems in dev-mode:
https://developer.github.com/v4/object/dependencygraphdependencyconnection/

**Comment by jonchurch** [comment]
Hijacking this thread because I believe this isn't relevant to MQTT and it's tests anymore (they appear to be passing now a days), but this still sounds like a great idea for a tool for this group to work on!

Specifically @Eomm's idea:

> The idea here is to create a tool that lists the users by stars and forks (desc) looking the "used by" function in GH, so maintainer can ask support to the top 10 users.

**Comment by jonchurch** [comment]
Turns out this was created, it’s https://github.com/pkgjs/dependents
