### ISSUE TITLE
Best Meeting Time for Highest Attendance

### ISSUE THREAD

**Issue by Emuentes** [nodejs/package-maintenance#225]
Looks like we could work on improving our meeting time-slot to improve attendance, let's discuss best times to meet below.

**Comment by mhdawson** [comment]
As reference the existing times are:

9 AM EST Monday 
3 PM EST Monday

We should also see if Monday is still the best day as well.   Mondays tend to have more overlaps with holidays (For example 2 weeks from now when our next meeting is, it's a holiday in Canada -> Canada Day)

**Comment by Eomm** [comment]
For me Monday or Tuesday is good, but my time is >=13 PM EST _(19:00 Rome)_

**Comment by rxmarbles** [comment]
I can't attend the 9 am EST due to it being like 6am my time and I'm either get the family ready for the day. I can attend the 3PM EST which is around my lunch time 😄

**Comment by mhdawson** [comment]
Would 9 and 2 EST alternating times on Tuesday's be better for people?

**Comment by ghinks** [comment]
yes, Tuesday is better for me too.

**Comment by Eomm** [comment]
> Would 9 and 2 EST alternating times on Tuesday's be better for people?

Do you mean 9 AM EST and 2 PM EST right?

**Comment by mhdawson** [comment]
@Eomm correct I should have added the AM and PM.

**Comment by ghinks** [comment]
I think the alternation on Tuesdays is a good idea. It give people a chance who have somewhat imposed schedules. Monday's are always super busy for most folks at work.

**Comment by mhdawson** [comment]
From last meeting proposal is

Alternating between 9 AM EST and 3PM EST on TUESDAY (same times but on Tuesdays)

Let us know what you think and we'll look to close on this in the next meeting.

**Comment by SathishGajendran** [comment]
9 AM EST is fine for me.

**Comment by wesleytodd** [comment]
I have been struggling to make the times, especially the early Monday morning time as that is 6am for me and usually before I am awake to check my calendar for the day.  Tuesday will make it more likely I will remember to wake up 💤

**Comment by wesleytodd** [comment]
I just noticed that the earlier time overlaps with the new [CPC meeting time](https://github.com/openjs-foundation/cross-project-council/issues/129), and the member overlap is pretty high.  I am not sure if we care to change it, but I just wanted to mention it.

**Comment by craftninja** [comment]
Discussed and agreed to switch over to Tuesday at 9 AM EST and 3 PM EST.

**Comment by mhdawson** [comment]
Meeting times changed in calendar, closing.
