### ISSUE TITLE
OpenJS Foundation project progression

### ISSUE THREAD

**Issue by dominykas** [nodejs/package-maintenance#238]
OpenJS Foundation has a [doc on how can projects join it](https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md), etc.

This probably has some overlap with what this group is working on (I haven't given it much thought yet, just making sure we start discussions around it).

**Comment by wesleytodd** [comment]
I have been following that group, and to me it seems like this is a good groundwork for [our phase 3](https://github.com/nodejs/package-maintenance/issues/144).  But maybe we would want to tone it back a bit, because their process is a bit daunting.

**Comment by mhdawson** [comment]
Agree it's good to consider but joining the Foundation is quite a bit bigger ask than "asking for help" so we should be careful on how hard it is.

**Comment by wesleytodd** [comment]
Completely agree, it is a much more bigger ask.  I didn't mean to downplay that, just that we are going for something different I think.

**Comment by dominykas** [comment]
Looks like we don't have a doc ready where it would make sense to include this information (the closest is [https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/DEPRECATE-GUIDELINES.md](deprecate guidelines), but deprecating is probably the opposite of joining a foundation...), but we do have some related issues:

* https://github.com/nodejs/package-maintenance/issues/155
* https://github.com/nodejs/package-maintenance/issues/144
* https://github.com/nodejs/package-maintenance/issues/4

For now - I'm closing this and we can hopefully include this in whatever the outcome of #155 and #144 is.
