### ISSUE TITLE
[axios] support opportunity analysis

### ISSUE THREAD

**Issue by Emuentes** [nodejs/package-maintenance#239]
It has been noted that responses to proposed changes from the Axios maintainers has been slower than users expect from a package with a similar volume of weekly downloads.

One such observation was noted here:
https://www.reddit.com/r/javascript/comments/cp5qhm/askjs_the_sad_state_of_axios/

We should reach out to them to discuss opportunities for us to positively impact their process flow.

Alternatively, we can work with them to onboard their project to our proposed "support levels" standard to set better clarified expectations that meet a community standard.

**Comment by thescientist13** [comment]
Hello!  We've recently landed #372 and add a section specifically speaking to Maintainer's now in the [README](https://github.com/nodejs/package-maintenance#for-maintainers) with some resources and ways you can reach out to the team directly with feedback / requests.  Please feel free to take the survey and we'll try our best to help out and / or communicate your needs to the wider community.  (ideally the survey would be taken by the project owner(s) ).

Let us know if you have any questions!
