### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by Eomm** [nodejs/package-maintenance#249]
Hi,
may I create some GH labels to organize a bit the issues?

I would like to create:

* `article`: issues related to blog post or other types of news where the target is spread this WG/work
* `tools`: issues related to tools to implement or implemented by this WG
* `vendor`: issues related to tools already in place that support a broad set of feature (ex: travis, npm, greenkeeper, etc..)
* `pilot`: issues related to pilot packages
* `discussion`: open discussion 

Other? Less? More? 😃

**Comment by Emuentes** [comment]
+1

**Comment by wesleytodd** [comment]
`top priority` & `good first issue`?

Those are both ones which we are going to start using on express and other places, as well as those being what I have as the [defaults in the status board](https://github.com/pkgjs/statusboard/blob/master/lib/config.js#L22).

**Comment by ljharb** [comment]
I also like “pull request wanted” to indicate that a PR for this issue is welcome (which isn’t always the case)

**Comment by Eomm** [comment]
Done: https://github.com/nodejs/package-maintenance/issues/labels

Checkout if is ok
I will close this issue lately the weekend after the labelling of the issue list 👍

**Comment by mhdawson** [comment]
@Eomm thanks !

**Comment by Eomm** [comment]
Done page 2

Feel free to adjust the labels if you don't agree in some association
