### ISSUE TITLE
Decide on contents for a package maintenance team "issue template"

### ISSUE THREAD

**Issue by Emuentes** [nodejs/package-maintenance#265]
Some tickets have lingered due to lack of consensus or clarity on the outcome that would justify the closing of the ticket.

In an effort to enable the team to confidently close tickets (or break them down into smaller scope, easier to manage parts) let's create an issue template to help streamline discussion practices.

**Comment by mhdawson** [comment]
In terms of merging a PR, in core we only require 2 approvals and 48 hours.  Something longer is probably appropriate here as its not code, but processes, policies etc but I'd say some like:

* at least 2 approvals
* no blocking review
* 7 days from time PR was opened.

**Comment by mhdawson** [comment]
Discussed in last meeting. This is what we agreed to be:

Least 4 approvals
No blocking review
7 days from time 4th approval was received.

Next step is to PR into README.md

**Comment by ghinks** [comment]
The rules above we added under PR https://github.com/nodejs/package-maintenance/pull/279
Now we have the rule in master we can close this in the next meeting.
