### ISSUE TITLE
Collab Summit Topic

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/package-maintenance#268]
Lets discuss!

Here is the issue template we will have to fill out:

```
<!--
Thank you! You are submitting a topic for the next Collaborator's Summit, Montreal 2019!

Please include as much detail as you are able to at this moment. Don't worry, it doesn't have to be complete.

Please feel free to link to any other issue, PR, or resource that could be relevant.
-->

**Topic of the session**

**Type of the session**
- [] Collaborate
- [] Workshop
- [] Talk


**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 


**Level**
- [] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.


**Describe the session**


**Session facilitator(s) and Github handle(s)**

<!--
Here's a handy [guide](https://github.com/nodejs/summit/blob/master/SESSION_FACILITATOR_GUIDE.md) for the person or persons who will facilitate this session.
-->


**Additional context (optional)**

```

Who can attend and what should we talk about?

**Comment by mhdawson** [comment]
I'll be there.

I'm kind of torn between "collaborate" and "talk". Ideally we'd have some time to collaborate but we also want to use the opportunity to evangelize and encourage new people to join as well.

**Comment by wesleytodd** [comment]
I also agree we have a dual purpose.  Could we call it "collaborate" but then start the session with a small presentation of the goals and current initiatives?  I have not been to a collab summit, so I don't know how strictly planned these are or need to be.

**Comment by mhdawson** [comment]
I think the 'Collaborate', 'Workshop', and 'Talk' distinction is new for this iteration.  Maybe we should ask about what it means to choose one versus another.  It may be to help people choose ones which are good for existing members of the WG versus new people.

**Comment by Eomm** [comment]
> Who can attend 

I think I can't go this time

> and what should we talk about?

The biggest topics are:
- the SUPPORT.md
- help the pilot packages
- reference to the written docs (do we think we are lacking in some aspect? (ci, publish, test etc.. are all covered)

I would like to finalize some tools I have in the backlog in order to start really helping the pilot packages in order to collect some data do present in the presentation at the beginning of the session

**Comment by mhdawson** [comment]
FYI - The submission link is being used for 2 purposes so we might want to make more than one proposal.  The first is for content in the "community corner" in the main conference, the second is for sessions in the collaborator summit itself.

**Comment by wesleytodd** [comment]
Can you describe "community corner" more?  What kind of content would we want to prepare?

**Comment by lholmquist** [comment]
> Who can attend 

I'm pretty sure i will be there and it will be my first collab summit

**Comment by mhdawson** [comment]
Last year "Community corner" was an area in the open area where there was a large monitor, mics etc setup. outside of the halls where the main tracks/talks took place.  Scheduled into that were more informal talks/sessions on community topics.

**Comment by wesleytodd** [comment]
So we need to have this finalized by ~Dec 4th.  Does anyone have any strong opinions on what we should do so we can start the application?

**Comment by mhdawson** [comment]
I think 2 submissions would be good.  

1) Community Corner  - promote interest to larger audience and try to attract new members)
2) Collab summit session  - working sessions of the group

Let's identify who will make the submissions in the meeting tomorrow.

**Comment by mhdawson** [comment]
# known to be there
* Darcy
* Michael
* Lucas
* Wes
* Bethany
* Glen (hopefully)
* Anybody else please comment

Book for 1 hour

Starting topics
- Publishing for teams
- Support info
- Discussion of funding platforms/approaches
- CI setup recommendations

Collab summit - who will submit
  - Michael to summit collaborator summit issue.
  - Edgar to submit the community corner issue and creates.  Those there will present.

**Comment by ruyadorno** [comment]
I'll make sure to attend those too 😊

**Comment by mhdawson** [comment]
Issue to propose the collab summit session: https://github.com/openjs-foundation/summit/issues/209

**Comment by mhdawson** [comment]
@Emuentes have you proposed the community corner session?

**Comment by ghinks** [comment]
Edgar and I will have a look at this, just reminding myself of what was said during the last meeting.

**Comment by ghinks** [comment]
@mhdawson I have just gone over the meeting from Nov 19th. I think both Edgar and myself are happy to propose and write up a community corner session. Is there a mechanism for this or should we just write something up under this issue? From the [main conference schedule](https://events19.linuxfoundation.org/events/nodejs-interactive-2019/program/schedule/) I am not sure where this would go?

**Comment by Emuentes** [comment]
@mhdawson @ghinks I proposed our community corner session here:

https://github.com/openjs-foundation/summit/issues/212

**Comment by mhdawson** [comment]
@ghinks @Emuentes thanks for submitting.  Looks good.

**Comment by mhdawson** [comment]
Collab summit happened closing.
