### ISSUE TITLE
PkgJS Org for WG supported tooling

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/package-maintenance#271]
As discussed in our meeting and in #263, we will be using the `@pkgjs` github org as well as npm namespace for publishing our tooling.  To kick things off we have a small todo list:

- [x] Change the licenses to MIT for existing repos
- [x] Assemble a list of contributors to grant access
- [x] Define a process for adding new members
- [x] Explicitly adopt the governance structure of the Node org for managing the projects
- [x] get these reviewed/landed #348
- [x] 2FA Publishing https://github.com/nodejs/package-maintenance/issues/244
- [x] Moderation team access
- [x] TSC members as owners
- [x] Add node js foundation account on npm

To start we can post users here who want to be added to that org as well as discuss what processes we need to document so that we are fully in line with the contribution and governance models Node has.

**Comment by dominykas** [comment]
✋ 

We need to move on solving that 2FA publishing problem ;)

**Comment by wesleytodd** [comment]
YESS! Added to the todo list!

**Comment by mhdawson** [comment]
I'd like to be added, but will need to wait until the licences are updated and then I can request the ok to contribute.

**Comment by Eomm** [comment]
I should have upgraded the licence to MIT for the 6 repo... great test in production for massive wax  😅

If you need more "broadcast" operation let me know!

**Comment by wesleytodd** [comment]
Ok, all the license changes are made and everyone from this thread so far is invited. 🎉

**Comment by mhdawson** [comment]
@wesleytodd thanks, requesting the ok to contribute to that org internally now :)

**Comment by darcyclarke** [comment]
@wesleytodd Quick Q: what was the original intent behind having a separate org spun up compared to pulling in net-new projects to `@nodejs`? It seems like we'll end up duplicating efforts to manage membership/auth/access.

**Comment by wesleytodd** [comment]
To follow up from our meeting today, the next steps for this is to raise this up to the greater Node community (maybe via the TSC?) and see how others are managing this and how we might make this official without loosing out on the reasons we thought a separate org was a good idea in the first place.

So, does anyone know of other teams/wg's which do this?  If so how are they managing it.  Also, should we raise an issue on the TSC repo to discuss?  It was brought up that @mhdawson probably has the best view of what the next steps should be.

**Comment by mhdawson** [comment]
@wesleytodd do we have a list of those reasons that we can use for the discussions? Most if not all of the teams I know of are using repos under the Node.js org.  

Can you also clarify what you mean by "official".  I thought one of the concerns that led to a separate org was avoiding the impression of it being official.

**Comment by wesleytodd** [comment]
>  do we have a list of those reasons that we can use for the discussions?

I think it was burried in an unrelated issue, I will dig for it and pull it into the OP here.

> Most if not all of the teams I know of are using repos under the Node.js org.

How many of them are producing tools like we want to build?  When I look at the repos in the node org I don't see much like what we have currently in `pkgjs`.  

> Can you also clarify what you mean by "official".

Official in this sense is about governance and ownership, and the thing we wanted to avoid was canonical implementation squashing competitive libraries.  I think these are separate meanings of "official".

**Comment by mhdawson** [comment]
@wesleytodd the closest is possibly node-addon-api, and nan.  Others repos for tools like https://github.com/nodejs/create-node-meeting-artifacts are more for internal use.   Mostly I was saying that other teams are using repos in the org, not that they are doing something similar.

In terms of "official", then what you might be asking is if the Node.js Project can 'own' and additional repo, with the TSC delegating management of it to the Package-maintenance team and ask that things like moderation be extended to this new org.  Is that a good way to describe it?

**Comment by wesleytodd** [comment]
> Is that a good way to describe it?

Yeah, described very well!

> Mostly I was saying that other teams are using repos in the org, not that they are doing something similar.

Got it.  I think that our differences matter here.  Internal tools don't really confer any sense of "official implementation" and things like nan are actually supported official projects.

**Comment by mhdawson** [comment]
Create this issue in the admin repo to start the discussion at the project level: https://github.com/nodejs/admin/issues/470

**Comment by dominykas** [comment]
I think there are two more aspects where the second org makes sense:

1. Just because we can create repositories in nodejs or pkgjs org, I don't want the new projects that are created there to feel like they're side-stepping the process of getting the foundation umbrella (mostly cause I'm not even sure what the implications are, but it would still feel unfair that an existing project would have to go through various stages and processes, etc, whereas our repos won't)
2. The above ties into the support levels - I think things like `nan` have the "backed by foundation" aspect, whereas the tooling that we're experimenting with are somewhat different?

**Comment by mhdawson** [comment]
Opened this to tweak governance. https://github.com/nodejs/admin/pull/484

We'll also need to request that the package maintenance team be chartered and delegated some ownership of the pkgjs repo unless we want to request repos using the existing process. This is an option but I think discussion with @wesleytodd gave me the impression that was not what the team wanted.

**Comment by andrewhughes101** [comment]
Hey, I was wondering if I could be added to the pkgjs org. It would help me continue working on the dependents tooling which is being moved to https://github.com/pkgjs/dependents

**Comment by wesleytodd** [comment]
@andrewhughes101 Added!

**Comment by mhdawson** [comment]
Issue opened for draft governance: https://github.com/nodejs/package-maintenance/pull/338

**Comment by BethGriggs** [comment]
@wesleytodd 👋 could I please be added to pkgjs? Planning to start working on `wiby` with @andrewhughes101

**Comment by dominykas** [comment]
@BethGriggs I don't have permissions for the org, but added you as a maintainer on wiby.

**Comment by vostrik** [comment]
@wesleytodd can I be added to pkgjs to work on tooling as member of Package Maintenance team? 

Now I have more time to work closer.

**Comment by wesleytodd** [comment]
Hey @vostrik, you can absolutely be added.  I will add you to the triage team for now, and then when you have some specific work in a repo we can get you setup on the appropriate teams.

**Comment by rodion-arr** [comment]
Hi all, if you need some help with tooling, please let me know, I will be happy to jump in

**Comment by wesleytodd** [comment]
@rodion-arr Do you have a particular project you would like to work on?  Happy to get you setup with on the triage team if you are unsure yet.  Let me know.

**Comment by rodion-arr** [comment]
@wesleytodd I did small contribution to `support` and a little bit familiar with `wiby`. I will be happy do some coding, but it is quite difficult for me to find here specific tasks to work on.

Anyway, I ready to spent some time in activities according to your priorities.

**Comment by wesleytodd** [comment]
Invite sent.  I think it might be a bit "self guided" right now, but if you have any ideas and want to get team feedback you can always open an issue to discuss what you are thinking.

**Comment by mhdawson** [comment]
PR with suggestion of initial administrative members:
https://github.com/nodejs/package-maintenance/pull/390

After we agree on the set of administrative members, I think the next step is to make sure we think the pkgjs org/repos meet the requirements we laid out in the governance and then move over the org, add access to the TSC etc.

**Comment by mhdawson** [comment]
Next steps:  

  * get these reviewed/landed https://github.com/nodejs/package-maintenance/issues/348
  * Add access as per governance
  * Integrated into Node.js org.

**Comment by dominykas** [comment]
Since all members already had that, I enforced 2FA in the pkgjs GH org.

Also updated @BethGriggs, @ljharb, @Eomm to owners and invited @ghinks as outlined in https://github.com/nodejs/package-maintenance/blob/master/ADMINISTRATIVE-MEMBERS.md

**Comment by helio-frota** [comment]
@wesleytodd could I please be added to pkgjs? Planning to work on all repos as long term thing (learning-n-contributing).

**Comment by helio-frota** [comment]
@wesleytodd thank you.

**Comment by dominykas** [comment]
- Added wiby, detect-node-support and dependents to the pkgjs npm org
- Created teams for the above
- Added https://www.npmjs.com/~nodejs-foundation to all of the above teams

**Comment by mhdawson** [comment]
Landed the on-boarding doc update to add TSC members to the pkgjs org as owners and to a team, and did the required additions for existing TSC members.

Next up do the same for the moderation onboarding documentation.

**Comment by mhdawson** [comment]
Landed updated documentation for moderation onboarding, and updated so moderation team members are owners of the pkgjs org.

**Comment by mhdawson** [comment]
Everything complete, closing
