### ISSUE TITLE
Publish baseline practices outside of this repo

### ISSUE THREAD

**Issue by dominykas** [nodejs/package-maintenance#273]
This came up as part of blog post related discussion (outside of here). When we reference the baseline practice (and other docs), do we want to link to the `master` on GH? Or should we publish them on some more permanent URL, e.g. on GH pages (or something trendier)? Or is it too soon?

**Comment by ljharb** [comment]
master seems fine to me for now; we can move it to gh-pages in the future tho.

**Comment by wesleytodd** [comment]
Agreed, `master` is good for now in that we don't plan to move the documents but want people to see the most up-to-date version.  If we do decide to move them ever we just need to be aware of where they are linked from so we can update.

**Comment by dominykas** [comment]
Closing for now - we can revisit later.
