### ISSUE TITLE
Node.js Foundation Package Maintenance Team - Express Triage Sync/Kickoff

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#284]
Initial meeting to discuss how to sync across team members and how to co-ordinate engagement

Set for 9 AM EST on Nov 25th. 

Discuss/sync on Express triage - kickoff - https://zoom.us/j/431077278
https://zoom.us/j/431077278

Will be led by @gireeshpunathil

**Comment by wesleytodd** [comment]
Hey, this sounds like a good idea but will be a bit difficult for me to attend.  It would be best to get a time where all the involved parties can attend, including members of the TC.  Could we maybe use this issue as a jumping off point for scheduling and setting an agenda?

Things I would like to discuss:

https://github.com/expressjs/discussions/issues/92
https://github.com/expressjs/express/pull/4055

**Comment by dougwilson** [comment]
I definitely cannot attend this as I will be on a plane at that time traveling for the holidays.

**Comment by gireeshpunathil** [comment]
I will setup a doodle shortly to gather consensus on timings.
@mhdawson - can you pls detach this item from the agenda? we could run this off the regular meetings.

**Comment by mhdawson** [comment]
@gireeshpunathil not quite sure what you mean by "detach for agenda".  But the discussion in the package-maintenance meeting is that we should find a different time so that Doug and or Wes can make it.

**Comment by gireeshpunathil** [comment]
@mhdawson - ah, sorry; I got confused - my understanding was that agenda item https://github.com/nodejs/package-maintenance/issues/284 was the one that was of interest to Doug and Wes.

**Comment by mhdawson** [comment]
@gireeshpunathil, yes they want us to reschedule this meeting so that they can attend. Can you co-ordinate a doodle to find a time that works for them?

**Comment by gireeshpunathil** [comment]
here is a doodle. The date is tentatively Dec 4th (that is movable), but more importantly, please cast your vote on a timing that works for you for future iterations as well.

https://doodle.com/poll/yhk89eqpuvuimiyb

@dougwilson @wesleytodd @helio-frota @mhdawson @HarshithaKp and anyone else who would like to take part. Thanks!

**Comment by gireeshpunathil** [comment]
ping @dougwilson - if we get your vote too, we can take it to the next level!

**Comment by dougwilson** [comment]
There wasn't a lot to choose from, but I voted now for what I could commit to actually making.

**Comment by gireeshpunathil** [comment]
@dougwilson - sorry about that! 

unfortunately, the list contain the maximum range I can accommodate myself (13 hours), and anything else is impractical for me.

however, looking at the current state of things, I don't see a slot that works for everyone. I am looking for ideas! 

 - select 2 times and run 2 meetings with timing changed in alternative sittings?
 - repoll with a band?
 - anything else?

**Comment by dougwilson** [comment]
Yea, I definitely understand :+1: the hardest part of course is that open source is unfortunately not the actual income generator, so I am beholden to my employer during my daytime hours. Sneaking comments on github during work is pretty easy but suddenly disappearing from work for an hour or so is not workable for me unfortunately. The rest of the hours are all the sleeping time in my timezone lol.

Now, with such different time zones, I'm not sure if maybe a weekend would work better for example? I could be up at say 3am on a weekend or even be on at normal work hours n the weekend too.

**Comment by mhdawson** [comment]
Based on the doodle, how about Gireesh get's together with Doug/Wes on Dec 3 10:30 slot and then again with the larger group on Dec 4 at 11:30.

Not ideal but hopefully Gireesh/Wes can convey the discussion that Gireesh/Wes/Doug have the day earlier?

**Comment by wesleytodd** [comment]
That seems fine to me.  We should make sure we have the Express youtube channel hooked in to stream all the meetings so we have a good record others can watch!  @dougwilson Could we get the access credentials added to the lastpass we used to share the OpenJSF zoom credentials?

**Comment by dougwilson** [comment]
AFAIK the creds to the youtube channel are just my personal gmail creds, if that is tue creds you're asking for. I didn't make a different gmail account or anything.

**Comment by dougwilson** [comment]
It looks like a YouTube channel can be moved to a different Google Account according to https://support.google.com/youtube/answer/3056283?hl=en . So I can move it to another Google Account, and seems like everything will stay intact. Is there like a general org account to move it in to or should we make a brand new Google Account just for this (and if so, how should we manage the 2FA on it)?

**Comment by gireeshpunathil** [comment]
ok, so that settles:

| Date | Time  | Timezone |
| ------------- | ------------- |-------------|
| Dec 4 | 9 - 10 AM  | IST |
| Dec 3 | 10.30 - 11.30 PM  |EST |
| Dec 3 | 7.30 - 8.30 PM | PST |

Let us use https://zoom.us/j/431077278

this is from node.js org, and has streaming facility.

I have sent out an invite (covering Wes now). @dougwilson - I don't have your email address, will you either share it with me here, or send me a private mail (my mail id is in my github profile). thanks!

**Comment by dougwilson** [comment]
> Not ideal but hopefully Gireesh/Wes can convey the discussion that Gireesh/Wes/Doug have the day earlier?

If the second conversation is just to convey the first, wouldn't just watching a recording suffice? Why even have two meetings?

> @dougwilson - I don't have your email address, will you either share it with me here, or send me a private mail (my mail id is in my github profile). thanks!

My public email is all over the place. As long as this us not the email I have to make an account under, then you're welcome to send it there: https://github.com/expressjs/express/blob/e1b45ebd050b6f06aa38cda5aaf0c21708b0c71e/package.json#L9

**Comment by mhdawson** [comment]
> If the second conversation is just to convey the first, wouldn't just watching a recording suffice? Why even have two meetings?

I don't think it's to just convey the first, but to be able to discussion questions and allow the larger group to organize/co-ordinate their efforts.  Watching the recording from the first one is a good way to prepare though.

**Comment by dougwilson** [comment]
Ok. Just trying to batter understand the purpose of splitting it. So what would the first one be about? Without questions that are going to be asked in the second ahead of time, what do we need the first for? Is there just some things that need information perhaps we can just get together in text?

I'm not asking because I don't want to have the meeting, but it seems like the first one is just for me to be there, so if I'm not there to coordinate / answer questions, what do we need it for is my question?

**Comment by wesleytodd** [comment]
> I have sent out an invite (covering Wes now).

I assume it is for more than just you and I right?  This happened a bit fast so I am just making sure I understand what we are discussing and who will be there.  Looking at the doodle and conversation here I am not sure who is attending in 5min and what we are discussing.

**Comment by wesleytodd** [comment]
I am on the call, just waiting for a host to start it.  @gireeshpunathil is that you?

**Comment by dougwilson** [comment]
@wesleytodd I think this is a day early. The post above says "Dec 3 | 10.30 - 11.30 PM | EST" in the able, which for me is tomorrow.

**Comment by wesleytodd** [comment]
Yeah I brought that up, but @gireeshpunathil sent my email a calendar invite, which was for now.  I guess I will drop from the call, but we should make sure the plan is clear for tomorrow.

**Comment by dougwilson** [comment]
Ok. I am around currently, so if it was actually supposed to be for tonight, I'm free to hop on 👍

**Comment by wesleytodd** [comment]
Same, I will log into the zoom account and see if I can start it.  At least then we can make sure we understand the goals and what we are already aligned on.

**Comment by wesleytodd** [comment]
Ok, @dougwilson and others, if you want to join this link I believe I started a webinar: https://zoom.us/j/177107150

**Comment by wesleytodd** [comment]
@gireeshpunathil, @HarshithaKP, @dougwilson and I had a good preliminary conversation.  Due to the scheduling issue we were not really prepared to stream and record it.  To post here while I have it fresh on my mind: https://github.com/expressjs/discussions/issues/92#issuecomment-561008388

**Comment by gireeshpunathil** [comment]
closing this, the the kick-off meeting with Doug and Wes happened, and actions identified + recorded.

I will open another issue to track a sync-up with the triage team members. thanks!
