### ISSUE TITLE
publish blog about publishing npm package

### ISSUE THREAD

**Issue by jchip** [nodejs/package-maintenance#285]
As result of https://github.com/nodejs/package-maintenance/issues/164 we landed a blog post https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PUBLISH-BLOG.md.

Let's schedule to publish this blog.

**Comment by ljharb** [comment]
We should try to add to it a section on using Travis shared configs

**Comment by jchip** [comment]
how is Travis shared config related to publishing npm package?

**Comment by ljharb** [comment]
@jchip oops, you're right, it's not - deleting my comment.

**Comment by mhdawson** [comment]
@jchip can you send me and email asking to get the Foundation staff to publish on the Node.js Medium blog. I'll forward along and we can see if we can get the process started.
