### ISSUE TITLE
Node/JS Interactive Community Corner Talk

### ISSUE THREAD

**Issue by ghinks** [nodejs/package-maintenance#295]
The [Node/JS Interactive conference](https://events19.linuxfoundation.org/events/nodejs-interactive-2019/program/schedule/) is taking place on 11th December 2019. The issue is being opened to allow the draft of the talk to be shared.

**Comment by Eomm** [comment]
Where I can find a recap or a recording?

**Comment by mhdawson** [comment]
The community corner ended not really being organized this year.  It was more of an informal chatting place versus talks.  Long way of saying there is no recording.

On the other hand when the recording from the collab summit come out there should be one from the package maintenance sessions.
