### ISSUE TITLE
Schedule First Meeting

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#3]
Planning for scheduling the first meeting.

Would like to plan for the week of Nov 26 which I know is a bit last minute, but it would let us kickoff some of the discussions and then hopefully have a second meeting ~ the week of Dec 17.

**Comment by mhdawson** [comment]
Doodle link for poll https://doodle.com/poll/9pubf77wuxf5irnm

**Comment by mhdawson** [comment]
Looks like trying for next week was just too optimistic.

New doodle for week of the 17th. https://doodle.com/poll/52shud6d23zmdepa.

This should give us enough time for people to arrange schedule, fill in availability. (I'm also away the first 2 weeks of December)

**Comment by balupton** [comment]
Did this happen? I would like to participate.

**Comment by mhdawson** [comment]
@balupton we are still ramping up with plans for the first meeting to be the week of Dec 17th. If you fill in your availability we'll factor that into the date selected.

**Comment by mhdawson** [comment]
I'll be selecting the meeting time on Dec 12th so please fill in the doodle before then.

**Comment by technetos** [comment]
Is the location still tbd?

**Comment by prettymuchbryce** [comment]
Will this meeting be recorded and/or notes taken and posted here afterwards?

**Comment by mcollina** [comment]
Yes the meeting will be recorded

**Comment by mcollina** [comment]
The meeting will happen on via Zoom and streamed over youtube.

**Comment by mcollina** [comment]
It shouldn’t, thanks.

**Comment by mhdawson** [comment]
Ok. Based on the doodle the best time is: Dec 17th at 3 EST.  Will create issue for meeting at that time.

**Comment by mhdawson** [comment]
First meeting added to foundation calendar and issue created here: https://github.com/nodejs/package-maintenance/issues/91.  Closing
