### ISSUE TITLE
Question: Is this part of a baseline practice? (link on description)

### ISSUE THREAD

**Issue by helio-frota** [nodejs/package-maintenance#301]
Hi,

Not 100% clear for me but want to know if this is part of a baseline practice:

https://medium.com/@nodejs/choosing-the-node-js-versions-for-your-ci-tests-hint-use-lts-89b67f68d7ca

If not, no problem but is good to know anyway.

thanks

**Comment by dominykas** [comment]
Yes, this recommendation is documented in https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/testing-guidelines.md

**Comment by helio-frota** [comment]
@dominykas thanks!
