### ISSUE TITLE
Axios Outreach

### ISSUE THREAD

**Issue by jonchurch** [nodejs/package-maintenance#322]
Hello package maintenance group 👋. I am not a member, but have been brought into the Express Triage effort based on what I believe were conversations that started here.

I wanted to note that I have commented on [an issue](https://github.com/axios/axios/issues/2747#issuecomment-593608470) at the Axios repo, mentioning to them the existence of this working group. 

**I hope that was okay, and I apologize if I have stepped out of line in doing so.**

My intent in filing this issue with you is to hopefully start a dialogue between these two projects, if both are willing ❤️ 

I was motivated by seeing the current state of their project. They seem to have put in work at some point in terms of creating [collaborator guidelines](https://github.com/axios/axios) and have brought folks in on an ad hoc basis. However, I get the feeling they could use some help, and they are currently sitting at a non-trivial amount of open issues and PRs.

I commented on an issue that a self-motivated community member created (@chinesedfan), who it seems has been doing a lot of triage work. That same community member had shared the following [comment](https://github.com/axios/axios/issues/1965#issuecomment-580177276) in a thread asking if the project was dead, and I think it shows very succinctly the challenges of getting involved and the value that sanctioning Triage can bring to a project:

> Share a personal story and some news for users in this thread,
> 
> * I noticed the situation of axios like you guys in Feb 2019 and triaged about 30 issues+pulls.
> * Got no responses from the maintainers and felt a little disappointed. But still kept an eye on it.
> * Luckily, I was invited as a collaborator in Dec 2019. That started my issue killer time. Total issues have decreased from ~600 to less than 300 now.
> 
> I created a plan for the next release. See [axios/axios/projects/4](https://github.com/axios/axios/projects/4). I know there are still some problems in axios, but I hope we can fix those hottest first.
> 
> I don't need your words to pay too much time on it, but would someone mind helping review those features when you are free, to make the next release better?

If their project is open to it, I think they could benefit from some of the learning that has been happening in the Express Triage, as well as the other conversations happening in this working group.

I see there was a prior issue https://github.com/nodejs/package-maintenance/issues/239 created about the possibility of reaching out to them.

**Comment by chinesedfan** [comment]
> My goal here is to ask: What do you need? Do you want help from other projects?

@jonchurch @wesleytodd Thanks for your messages left in [my issue](https://github.com/axios/axios/issues/2747), and the answer is absolutely YES. Let me introduce the background more.

- The owner of axios is @mzabriskie, who has quit from people's sight for a while.
- And @emilyemorehouse is the only member I used to meet in Github. We can ask her to release new releases, but she doesn't have time on the project directly.

Currently, I, a collaborator without too much permissions, have triaged every issue and pull request several times. As you can see, at least noisy ones are closed and the rest is marked with different labels. I think the burden of maintaining or triaging is still acceptable for me. But what we are eager to is more professional and active reviewers to help axios fix bugs and implement features.

#239 has been opened for months. I have a curious question. Is no further actions from [nodejs/package-maintenance](https://github.com/nodejs/package-maintenance) due to no feedbacks from axios? Now it will be changed. :)

**Comment by thescientist13** [comment]
Thanks for reaching out @chinesedfan and appreciate all the work you've been doing on behalf of the Axios project.  🌟 

From this team's perspective, one thing that would really help in establishing a good collaborate engagement here would be if the owner of Axios could be involved.  Do you know if anyone has been in contact with @mzabriskie recently?  If the project is looking for some guidance around governance and ownership, these options may be limited without @mzabriskie's direct involvement, is all.

We are of course happy to share our experience / documentation already available in our repo, but for anything more, it would be important to have key project stakeholders involved as well.

Let us know your thoughts.

**Comment by jonchurch** [comment]
For some more context around axios' impact and stakeholders, some of the top users are Gatsby, Twilio, and Nest. Perhaps once upon a time Google used it for it's Node API libraries, seeing as they have forked it over to [`gaxios`](https://www.npmjs.com/package/gaxios).

**Comment by thescientist13** [comment]
Hey @jonchurch !

I followed up [here](https://github.com/nodejs/package-maintenance/issues/239#issuecomment-664046080) as well, but just wanted to let you know we've recently landed #372 and add a section specifically speaking to Maintainer's now in the [README](https://github.com/nodejs/package-maintenance#for-maintainers) with some resources and ways you can reach out to the team directly with feedback / requests.  Please feel free to take the survey and we'll try our best to help out and / or communicate your needs to the wider community.  (ideally the survey would be taken by the project owner(s) ).

Let us know if you have any questions!
