### ISSUE TITLE
Submit sessions to Collab Summit

### ISSUE THREAD

**Issue by ruyadorno** [nodejs/package-maintenance#335]
Same format as the last Collab Summit in Montreal, just head over to https://github.com/openjs-foundation/summit/issues and submit a new issue following the template there 😊 

This time we're also trying to have a [New Contributor Orientation Track](https://github.com/openjs-foundation/summit/issues/251) so keep in mind it would be awesome to have some onboard sessions too.

**Comment by wesleytodd** [comment]
Ok, issue created based on what we chatted on on the call today.  https://github.com/openjs-foundation/summit/issues/275

**Comment by ghinks** [comment]
yes, @wesleytodd I'm fully committed.

**Comment by ghinks** [comment]
I have a [draft set of slides](https://slides.com/glennhinks-1/package-maintenance). Slides.com allow a limited number of collaborators and so ping me to get added to make changes etc.

[package-maintenance (1).pdf](https://github.com/nodejs/package-maintenance/files/4825023/package-maintenance.1.pdf)

**Comment by thescientist13** [comment]
Looks good!  Hope the session goes well.  

—
Owen Buckley
https://www.thegreenhouse.io/
978-413-0134

**Comment by ghinks** [comment]
thanks Owen. We have some organizing today today.

**Comment by thescientist13** [comment]
This can probably be closed now?
