### ISSUE TITLE
[docs] testing guidelines (draft)

### ISSUE THREAD

**Issue by thescientist13** [nodejs/package-maintenance#344]
In #333 a Table of Contents was added for helping readers and maintainers with organizing content within the docs/ folder.

In that ToC it was observed that [content exists](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/testing-guidelines.md) for this topic already but it is in **draft** status currently.  This issue is for tracking the action items needed (if any) to promote this out of draft status.

**Comment by dantecruz** [comment]
Done

**Comment by yansiling** [comment]
瓦特？

**Comment by yansiling** [comment]
搞毛？

**Comment by dantecruz** [comment]
Hi Yansling,
Sorry can't read Chinese just type something for test.

**Comment by yansiling** [comment]
Good,But I am a Chinese,My English is very poor

**Comment by dantecruz** [comment]
Dear Yansling,

 

No worries everything can learn just keep communicating it will be great. By the My name is Dante from Macau.

 

Best regards,

Dante Dela Cruz

Vastcom Technology Limited

Alameda Dr. Carlos D’Assumpcao 249-263,

China Civil Plaza, 15-AND-G, Macau

**Comment by yansiling** [comment]
Thank you. I will learn English well.



---Original---

**Comment by dominykas** [comment]
Just a note that we also have https://github.com/nodejs/package-maintenance/issues/157 - not sure if there's overlap, or you want to specifically address draft state here.

**Comment by dominykas** [comment]
(deleted some spambots having a conversation between themselves - I'm not against machine-persons, just that the conversation was offtopic)

**Comment by thescientist13** [comment]
Hey @dominykas .

Yes, this was more to understand if the team still considered the current state of the doc a draft, or if it was complete "enough" to promote out of a draft state.  

I didn't see that issue before so It sounds then that there is still active work happening on that topic to get it out of draft status?  If so, then I think we can close this issue out, and just request those working on #157 to do the following when they submit a PR:
1. Move the document out of draft folder
1. In the docs README table of contents:
    - Remove the draft designation
    - Update the file path link

**Comment by thescientist13** [comment]
PR opened here
https://github.com/nodejs/package-maintenance/pull/377

**Comment by mhdawson** [comment]
Seems like we can close this one, since #377 is landed
