### ISSUE TITLE
[docs] package support (draft)

### ISSUE THREAD

**Issue by thescientist13** [nodejs/package-maintenance#346]
In #333 a Table of Contents was added for helping readers and maintainers with organizing content within the docs/ folder.

In that ToC it was observed that [content exists](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md) for this topic already but it is in **draft** status currently.  This issue is for tracking the action items needed (if any) to promote this out of draft status.

**Comment by mhdawson** [comment]
PR to move https://github.com/nodejs/package-maintenance/pull/375/files

**Comment by thescientist13** [comment]
thanks @mhdawson !
