### ISSUE TITLE
[docs] tools (draft)

### ISSUE THREAD

**Issue by thescientist13** [nodejs/package-maintenance#347]
In #333 a Table of Contents was added for helping readers and maintainers with organizing content within the docs/ folder.

In that ToC it was observed that [content exists](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/ci-cd-guidelines.md) for tools developed by this group but it is in **draft** status currently.  This issue is for tracking the action items needed (if any) to promote this out of draft status.

**Comment by Eomm** [comment]
I think we should mention the [@pkgjs](https://github.com/pkgjs/) org and create a bridge between the guidelines we are promoting and the tooling we can provide to apply those guidelines.

I think the draft of the docs, is related to the tools, for example, when [PACKAGE-SUPPORT.md](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md) will exit from the draft, we could approve this "T<i>ooling</i>OC" aswell

**Comment by thescientist13** [comment]
_tools.md_ removed in #421
