### ISSUE TITLE
New repository for testing dependents

### ISSUE THREAD

**Issue by andrewhughes101** [nodejs/package-maintenance#352]
As per https://github.com/nodejs/package-maintenance/issues/327#issuecomment-620147653 I think we need a new repository for the testing tool. Im proposing we create a new repository called `dependents-testing` in the pkgjs org, as per the process in https://github.com/nodejs/package-maintenance/pull/338, if there are no objections in the next 72 hours, I will create the repo.

**Comment by dominykas** [comment]
Sorry I took 3 days to respond... I suppose I can create the repo and we can rename it later, but how about we find another name for it?

`citgm` is already taken by node, so to avoid confusion I was thinking something else. 

One early idea I had was "what-if-you-use-this" (`wiyut`).

**Comment by ljharb** [comment]
"will i break you"

**Comment by addaleax** [comment]
I know the package isn’t exactly popular, but I have been using it for a few years now on projects and it seems to do exactly what you are going for here: https://www.npmjs.com/package/reverse-test

**Comment by ljharb** [comment]
Ooh, fancy! I can't get it to produce any output unless i pass a package name tho :-/

**Comment by addaleax** [comment]
@ljharb Yeah, looks like https://github.com/chrisdickinson/npm-get-dependents is quite outdated at this point :) I can try to see if I can update that, but I think for testing in CI you’d probably want fixed module names anyway

**Comment by dominykas** [comment]
Adding to agenda - let's make a decision if we want to create the repo as is, or with a different name, or fork, or wait, if that's OK @andrewhughes101?

**Comment by dominykas** [comment]
Created https://github.com/pkgjs/wiby and added @andrewhughes101 as a maintainer (until we get a better too to manage permissions).
