### ISSUE TITLE
supported vs maintained

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/package-maintenance#353]
From original issue: https://github.com/pkgjs/nv/issues/7

As noted in the README, there isn't a canonical reference yet, but raising an apparent terminology variation in the current draft documents. (This may have been resolved in a discussion I didn't find.)

`nv` supports an alias for `maintained`, but https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md#node-name-space lists a target alias of `supported`

cc @shadowspawn 

---

@nodejs/package-maintenance Anyone want to take a look at addressing this?

I also think we should consider moving what is documented in this issue into a document of it's own then reference it from the package support proposal. I say this because I think we should move faster on the standardized grammar than the support work (which has been stalled lately). Thoughts?

**Comment by mhdawson** [comment]
@wesleytodd not sure you think we should change the terminology in PACKAGE-SUPPORT.md or in nv ?

**Comment by Eomm** [comment]
`supported` should be updated
Here the result of the discussion https://github.com/nodejs/Release/issues/359#issuecomment-529945684 

> We discussed in the package-maintenance meeting today and I've submitted a PR to change maintained to supported based on this feedback. nodejs/package-maintenance#257

I will open a PR to pkgjs 👍

**Comment by shadowspawn** [comment]
The PACKAGE-SUPPORT document is out of draft (and uses `supported` as per previous comments):
https://github.com/nodejs/package-maintenance/blob/master/docs/PACKAGE-SUPPORT.md

**Comment by dominykas** [comment]
The decision in https://github.com/nodejs/Release/issues/359 and https://github.com/nodejs/Release/pull/517 uses `supported`, so does the PACKAGE-SUPPORT document - unless there's any objects I'll close this issue in a week or so?
