### ISSUE TITLE
Meeting to agree/discuss next steps for https://github.com/pkgjs/support

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#355]
Would like to get those who have contributed to https://github.com/pkgjs/support
together so that we can upadte to be consistent with our current version of the
support info.

@Eomm , @wesleytodd, @BethGriggs 

Doodle for meeting time: https://doodle.com/poll/z9t2iy9fqgen7p4u

**Comment by wesleytodd** [comment]
doodle ✅ 

Would it be helpful to get maintainers for `nvm` and `n` in the conversation?  With @BethGriggs from build and myself for `nv`, if we had @ljharb and @shadowspawn we could probably also knock out the requirements from the build output to get the alias support in those tools.

**Comment by wesleytodd** [comment]
To be clear, why I thought this was happening was to clarify the recent issue with the node version aliases in the support spec.  On second thought, that might not have been your intent.  Did I mistake the point of this issue?

We still need to have that other conversation, but sorry if I tried to mix to separate things!

**Comment by mhdawson** [comment]
My intent was to talk about the tool to generate/validate the support info to get that unblocked.

**Comment by mhdawson** [comment]
Setting meeting time as 3pm EST on Thursday since that seems to the time everybody who has chimed in is free.  We'll use the standard URL for the package maintenance meetings. https://zoom.us/j/431077278

**Comment by mhdawson** [comment]
Meeting held, MVP documented in: https://github.com/pkgjs/support/issues/6
