### ISSUE TITLE
node-fetch is looking for help

### ISSUE THREAD

**Issue by jonchurch** [nodejs/package-maintenance#360]
Ran into [this issue](https://github.com/node-fetch/node-fetch/issues/772), wanted to post here in case it overlaps with any discussions happening, or if there's interest. 

I'm not entirely sure of the situation, but it looks like there is/was a change of maintainership, or it's in the process.

The linked issue is specifically a call to action for Triage.

I haven't opened an issue with them or anything, but wanted to catalogue this here.

**Comment by thescientist13** [comment]
Thanks @jonchurch .  Hoping this can be reviewed in the next meeting agenda in the context of some docs we are working on and general process around how this team can help package maintainers in the ecosystem, be it docs, tools, or some other level of support.

**Comment by larson-carter** [comment]
@jonchurch I made a comment on the issue reaching out saying I'm down to help. It appears that they are receiving other volunteers also.

**Comment by wesleytodd** [comment]
Glad folks are stepping up.  We are working on setting up a session for the upcoming collab summit to present what we have been working on and how projects can work with us.  I would recommend some folks from `node-fetch` try to attend.  We only have the rough proposal, but we will post links once the schedule is announced.

**Comment by larson-carter** [comment]
@wesleytodd Sure, share that link and any other information that you have. I will then route it to the rest of them.

**Comment by xxczaki** [comment]
Sorry for a late reply, I saw this issue 5 minutes before the end of the stream :cry:

**Comment by thescientist13** [comment]
Just wanted to let everyone know we've recently landed #372 and add a section specifically speaking to Maintainer's now in the README with some resources and ways you can reach out to the team directly with feedback / requests. Please feel free to take the survey and we'll try our best to help out and / or communicate your needs to the wider community. (ideally the survey would be taken by the project owner(s) ).

Let us know if you have any questions!
