### ISSUE TITLE
pkgjs housekeeping: AUTHORS / LICENSE files

### ISSUE THREAD

**Issue by dominykas** [nodejs/package-maintenance#368]
Following up some questions from https://github.com/nodejs/package-maintenance/issues/348 and things we discussed in the meetings. I think this one is probably for legal, right @mhdawson?

- The (c) authors part in some `LICENSE` templates says e.g. "ci-travis-config contributors", in some others it says "Copyright Node.js contributors". Can we stick to just "Copyright Node.js contributors." (so that it's easy to copy/paste the `LICENSE` file) or does it have to spell out each repo name?
    - We can probably skip the year, as the main license file doesn't have it?
- The `ci-config-*` repos have the `AUTHORS` file added there. Is that file necessary?
    - The list of contributors is always there in the git history? We can probably enforce that the `master` cannot be overwritten?
    - If the file is actually necessary - does the org already have a tool to generate it? Are there any rules around what should go into it? Can we simply add a link to the Github "Contributors" tab and be done with it or does it have to be provider agnostic and have an actual list of people?
- In some cases we have a link to that `AUTHORS` file from the `LICENSE`. Is that _link_ necessary? The https://github.com/nodejs/node/blob/master/LICENSE itself does not have it.

**Comment by mhdawson** [comment]
This is still draft but I think answers a number of the questions: https://github.com/openjs-foundation/cross-project-council/pull/414/files

I think it says
* skip the year -> yes


In terms of needing an `AUTHORS` file or not, I'm not sure @brianwarner can you clarify that?

**Comment by mhdawson** [comment]
In terms of just using "Copyright Node.js contributors.", I'm not sure that's correct as the AUTHORs listed for Node.js may not include people who have contributed to pkgjs.

**Comment by ljharb** [comment]
Can’t we just say “contributors”? Most projects don’t have an authors file and aren’t that specific about it.

**Comment by brianwarner** [comment]
Yes, best to just use "Node.js contributors".

**Comment by ljharb** [comment]
I even meant, unqualified - just the word “contributors”

**Comment by brianwarner** [comment]
We recommend keeping at least the project name. But these lines are mainly a courtesy in the grand scheme of things, so it's not a big deal either way. 

"Copyright notices are not mandatory in order for the contributor to retain ownership of their copyright." 

https://www.linuxfoundation.org/blog/2020/01/copyright-notices-in-open-source-software-projects/

**Comment by dominykas** [comment]
> Yes, best to just use "Node.js contributors".

Just to clarify, can we use "Node.js contributors" for _any_ project under nodejs/pkgjs orgs, or do we have to say "wiby contributors" for [wiby](https://github.com/pkgjs/wiby)?

**Comment by dominykas** [comment]
Discussed during #371, came to a proposal to use the following for the (c) line:

```
(c) Contributors [link to the Github's contributors page]
```

@brianwarner is that good enough?

**Comment by brianwarner** [comment]
Sure, that looks like it would work, and is a clean and efficient way to show where it came from. It also fits with the idea of keeping minimal info here, as it's less likely to get stale over the years. I'd say go for it!

**Comment by dominykas** [comment]
Thanks!

**Comment by dominykas** [comment]
Opened all the relevant PRs, closing this.

Thanks everyone for the input.
