### ISSUE TITLE
Triage team for `pkgjs`

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/package-maintenance#378]
I think we should establish a triage team in `pkgjs`.  I would propose that every member of the package maintenance team be added.  It would give label and issue management to all the repos.  Thoughts?

**Comment by ghinks** [comment]
sounds like a good idea.

**Comment by lholmquist** [comment]
+1

**Comment by wesleytodd** [comment]
Cool, will let this sit for a day to make sure no one has opposition, then I will make it and invite everyone!

**Comment by larson-carter** [comment]
This is something that would make our work a lot more efficient! I love it!

**Comment by ghinks** [comment]
ok folks I'm going to bring up this team during my work meetings as a good place to get started in open source.

**Comment by wesleytodd** [comment]
Ok, triage team created and everyone who had accepted their membership invite was added.  If you want to be on that team and are not, comment here and I will add you.

https://github.com/orgs/pkgjs/teams/triage

**Comment by larson-carter** [comment]
@wesleytodd Can I get an invite to that team?
