### ISSUE TITLE
Adding Package Maintenance to NodeJS website

### ISSUE THREAD

**Issue by rxmarbles** [nodejs/package-maintenance#402]
I am working on a PR to add our WG to the nodejs website however looking at our README for about this group and our repsonsibilities it seems a bit outdated. I would like to open a discussion on what your blurb should be in the NodeJS website so we can add ourselves since we have been charted since July. Any thoughts?

**Comment by thescientist13** [comment]
Which parts did you have in mind and / or do you consider outdated (or otherwise don't reflect the original charter)?  I am fairly new to the team so knowing the long tail of the group's growth and evolution would be helpful context (at least for me anyway).  

On the surface it seems fairly accurate.  😊

**Comment by Eomm** [comment]
I think the Goals are fine.

I would just add something like:

> Listen to the community's need and help vendors to define and spread new standards

(thinking on our work on the package `support` field)

**Comment by rxmarbles** [comment]
@Eomm I like the way that sounds for the general blurb. @thescientist13 I was just looking at the other WG's in the nodejs website kinda like https://nodejs.org/en/about/working-groups/#security and their brief description is a good description compared to our README intro:  
```
Repository for discussion on how to help ensure baseline maintenance and ability to safely use key packages in the ecosystem with current Node.js versions. You can find more about this initiative in the article: Call to Action: Accelerating Node.js Growth
```

This may work for our README and this Github repo, but in terms of just a general blurb about what this WG is responsible for or works towards (which is why i think @Eomm's suggestion makes sense for th general blurb)

**Comment by mhdawson** [comment]
I think @Eomm suggestion was that the goals needed to be expanded with that extra line as opposed to that being the general description for the working group.  

How about the following for the general description

The package maintenance working group brings together node.js collaborators, package maintainers,  and package consumers to work together with the goal of ensuring the health of the package ecosystem.

**Comment by rxmarbles** [comment]
@mhdawson I'm game for that description w/ the goals being added for additional reference.

**Comment by Eomm** [comment]
> I think @Eomm suggestion was that the goals needed to be expanded with that extra line as opposed to that being the general description for the working group.

Exactly, I didn't get it that @rxmarbles was looking for a brief description

**Comment by rxmarbles** [comment]
@nodejs/package-maintenance I reviewed the meeting notes. If there are no objections I will close this issue and open a PR in the nodejs website w/ @mhdawson 's suggestion
