### ISSUE TITLE
Technical Sync on create-pkg

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/package-maintenance#406]
The next steps on #404 is to build a technical plan for the tool.  Anyone who is interested in this effort, please react below with the time which works best for you.

👍   Wednesday Sept 9th @ 10am ET (7am PT)
🎉  Thursday Sept 10th @ 10am ET (7am PT)
❤️  Thursday Sept 10th @ 12pm ET (9am PT)

We will to over the notes from #404 and then discuss the implementation plan.  The goal is to arrive at a scope of work, and agree on some implementation details.

cc: @nodejs/package-maintenance

**Comment by wesleytodd** [comment]
I posted some ideas I have been thinking, which might be a good place to start the conversation: https://github.com/pkgjs/create/issues/7

**Comment by wesleytodd** [comment]
Thursday@12 seems to be the winner, if that time is a hard no for anyone (@darcyclarke I see you selected wednesday, and being an important voice in this I want to make sure you can attend) speak up.  Also, sorry for the late notice, I realized that todays time is already past lol.

**Comment by mhdawson** [comment]
Sorry for the late vote, but I can may Thurs at 12, who is going to send out a link?

**Comment by wesleytodd** [comment]
No worries, it was a late poll.  I only have OpenJS credentials for Zoom, do you want to create a link @mhdawson, or we can use the foundation account and I can make it.

**Comment by thescientist13** [comment]
Looks like my work schedule freed up a bit, so should be able to join today at 12 ET as well.

**Comment by darcyclarke** [comment]
@wesleytodd don't worry about me. I can make the call today ❤️

**Comment by wesleytodd** [comment]
I can start the call on the Foundation account if noone with the node account is around.  Grabbing a zoom link now.

**Comment by wesleytodd** [comment]
Here we go: https://zoom.us/j/97530914041

**Comment by mhdawson** [comment]
I seemed to have messed up my times and missed it sorry.

**Comment by wesleytodd** [comment]
https://www.youtube.com/watch?v=z6tY40R5Dws
