### ISSUE TITLE
Meeting to discuss - https://github.com/nodejs/package-maintenance/issues/386 - Wed Sep 16 11 EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#408]
I've created this issue to vulnerability management as per #386.

@nodejs/package-maintenance FYI, we'll use the same link as for regular meetings:

https://zoom.us/j/431077278

**Comment by dominykas** [comment]
That's New York time, right?

**Comment by ljharb** [comment]
How was this time selected? I’d love to attend but that’s a bit early for me.

**Comment by mhdawson** [comment]
I tried to find a time where we'd have people from Synk and npm, its very hard so I pinged them directly and came up with this.  

Yes New York time.

**Comment by mhdawson** [comment]
and correct on EDT.  I should just say Easter as I never remember what we are currently under.

**Comment by mhdawson** [comment]
Meeting held, closing.
