### ISSUE TITLE
Suggested list of modules to help get support info into

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#413]
Add the suggestions. volunteer here

**Comment by boneskull** [comment]
@mhdawson Can you please provide some more context here?  What am I volunteering for? :smile:

**Comment by mhdawson** [comment]
This has the ask: https://openjsf.org/blog/2020/09/23/node-js-package-maintenance-bridging-the-gap-between-maintainers-and-consumers/

This issue is to track the modules we'd like to prioritize to add support info to.

**Comment by mhdawson** [comment]
I'm going to work getting it added to node-addon-api.

We should also make sure to add to all of the modules in pkgjs.

**Comment by mhdawson** [comment]
PR to add support info in node-addon-api -> https://github.com/nodejs/node-addon-api/pull/843

**Comment by mhdawson** [comment]
The PR to add to node-addon-api landed.

Its been added to the modules in github/nodeshift.

**Comment by shadowspawn** [comment]
Support info has been added to https://github.com/tj/commander.js

**Comment by mhdawson** [comment]
@shadowspawn thanks !

**Comment by thescientist13** [comment]
Curious @mhdawson what, if any, remaining action items are left on this?  If there are some, a quick summary status may be helpful for those coming into this issue and how contributions to help complete it may be supported, if applicable.

**Comment by mhdawson** [comment]
@thescientist13 we still need to figure out how to get more packages/modules to adopt. Having said that, this issue being on the agenda is not helping to move that forward so I'd be ok with closing it until I have more time to define some more concrete next steps.

**Comment by thescientist13** [comment]
Should we curate a list of packages for us to do outreach to for this, potentially sourced from our list of identified high impact packages from our[ Pilot Program List](https://github.com/nodejs/package-maintenance/issues/142#issuecomment-462184096)

**Comment by ljharb** [comment]
I'm no longer abreast of where our tooling is, but if there's a one-liner command i can run to make all the changes required in a git working directory, I can start doing it in my 350 packages. Do we have that yet?

**Comment by mhdawson** [comment]
@ljharb This is the tooling we have - https://github.com/pkgjs/support.  Let us know if you have questions/that does not do what you are looking for.

**Comment by ljharb** [comment]
The tool includes "best-effort", but https://github.com/nodejs/package-maintenance/blob/HEAD/docs/PACKAGE-SUPPORT.md does not - did we remove that since it's basically the same as "time-permitting"?

**Comment by mhdawson** [comment]
@ljharb what version are you using? This commit - https://github.com/pkgjs/support/commit/597303a1dc1640af25aea5abf78d8d4c36538603

removed best-effort

If you are using 0.0.5 that means I should publish a new version.

**Comment by ljharb** [comment]
I'm using whatever's latest; that commit is indeed unreleased.

**Comment by mhdawson** [comment]
@ljharb published a new version of the support package.

**Comment by mhdawson** [comment]
I'm going to close this in favor of trying to find some more specific actions/issues.
