### ISSUE TITLE
Confirm/re-evaluate meeting times/schedule?

### ISSUE THREAD

**Issue by ljharb** [nodejs/package-maintenance#438]
During today's call, we talked briefly about whether the current meeting cadence/timing was meeting our needs. I have no personal opinion here - i'm happy to miss every other meeting for the sake of timezone equity :-) - but it seems useful to make sure that:
 - everyone who wants to attend meetings regularly has convenient times to do so
 - each meeting time is generating sufficient attendance so as to provide value to the group

 If these are currently being met, no changes are needed.

Thoughts?

**Comment by mhdawson** [comment]
I'm ok with the current times, but being in EST it's easiest for me, we'll want the input from those at the far ends of the range.

**Comment by Eomm** [comment]
It would be doable for me to join at UTC 19:00

I'm in the EU / Central tz (21:00) and this timeframe has become impossible for me 😞

**Comment by BethGriggs** [comment]
Similar for me, the later time is just a little bit too late for me to regularly join.

**Comment by ghinks** [comment]
I too am ok with the current times. It has been a busy end of year for me. I will be attending going forwards.

**Comment by thescientist13** [comment]
I'm also EST, so currently both of the meeting times are fairly accommodating to me at the moment, but am flexible, assuming there are no work meeting conflicts.

**Comment by mhdawson** [comment]
A few proposals are to move the 3PM EST on Tuesdays

* Thursday at 12 EST on the weeks the Community Committee is not held or
* Thursday at 1 EST on the weeks the Web frameworks team does not meet

Darcy will setup a doodle to get input on those 2 timeslots.

**Comment by darcyclarke** [comment]
As per the call on Tuesday, I made a quick Doodle Calendar w/ some of the suggested timeslots (let me know if this doesn't include every time we mentioned previously): https://doodle.com/poll/hhqi2u4gw687yfqa#table Feel free to check which times you think work best (they include the existing two timeslots we're using)

**Comment by darcyclarke** [comment]
Doodle Calendar: https://doodle.com/poll/cy7ip6bizy3c9y5u Feel free to mark which timeslots work best for you

**Comment by styfle** [comment]
Tuesdays are usually pretty booked for me so I voted for the Thursday time slots.

**Comment by thescientist13** [comment]
@darcyclarke / @ljharb 
Is the proposal intended to consolidate all meetings times to be the same day / time of the week?  

Currently the meeting times alternate between the following :
- Tuesday, @9am EST
- Tuesday, @3pm EST

I wasn't sure if the issue / doodle is aiming to:
1. adjust one of the existing times 
2. align both meetings to be the same

I am fine with both way, but was just curious how the replies to the doodle will be applied to the current cadence.

**Comment by mhdawson** [comment]
@BethGriggs, @wesleytodd, @ruyadorno @nodejs/package-maintenance can you fill in the doodle so we can close on an updated time next week.

**Comment by mhdawson** [comment]
Based on the doodle we agreed to move the Tuesday 9 AM time to Thursday at 1-2 ET as well as keeping the current Tuesday 3-4 time, that covers the two most popular times and has at least one time that everybody who responded can make.

**Comment by mhdawson** [comment]
Meeting moved.
