### ISSUE TITLE
Team membership audit

### ISSUE THREAD

**Issue by dominykas** [nodejs/package-maintenance#497]
As suggested by @ljharb in https://github.com/orgs/nodejs/teams/package-maintenance/discussions/1:

> We should probably audit the github team list, and remove folks who've been inactive (ie not on github, slack, or in meetings), who also don't express a wish to remain?

**Comment by mhdawson** [comment]
+1

**Comment by ghinks** [comment]
Agreed. During the first couple of days there were hundreds as I remember. We may also need to do a bit more to recruit.

**Comment by mhdawson** [comment]
Related - https://github.com/nodejs/package-maintenance/issues/499

**Comment by dominykas** [comment]
I went through [the team](https://github.com/orgs/nodejs/teams/package-maintenance/members) and https://github.com/nodejs/package-maintenance/blob/main/MEMBERS.md, and the following people are no longer in the MEMBERS.md, but remain in the team:

- https://github.com/indexzero
- https://github.com/mcollina
- https://github.com/aoberoi
- https://github.com/boneskull
- https://github.com/gabrielschulhof
- https://github.com/TheHollidayInn
- https://github.com/wentout
- https://github.com/jchip
- https://github.com/craftninja
- https://github.com/bluesockets
- https://github.com/gentios
- https://github.com/jonchurch

**Comment by dominykas** [comment]
Updated. Happy to re-add if anyone was removed by mistake.
