### ISSUE TITLE
Membership audit - please respond

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#499]
We are doing a membership audit as suggested in https://github.com/nodejs/package-maintenance/issues/497.  Unless you have been in a recent meeting or respond to this issue within the next 30 days, we'll assume it's ok to move you to emeritus.

Michael Dawson (@mhdawson)
Matteo Collina (@mcollina)
Christopher Hiller (@boneskull)
Matt Edelman (@grawk)
Franziska Hinkelmann (@fhinkel)
Refael Ackermann (@refack)
Jordan Harband (@ljharb)
Charlie Robbins (@indexzero)
Monica EnePietrosanu (@menepie)
Arunesh Chandra (@aruneshchandra)
Mohammed Essehemy (@MohammedEssehemy)
Emily Platzer (@craftninja)
Viktor Vershanskij (@wentout)
Kyle Martin (@js-kyle)
Wes Todd (@wesleytodd)
Pooya Parsa (@pi0)
Pavel Vostrikov (@vostrik)
Larry Lu (@Larry850806)
Osmond van Hemert (@ovhemert)
Nairi Harutyunyan (@nairihar)
Edward Snare (@edwardsnare)
Joel Chen (@jchip)
Kenigbolo Meya Stephen (@kenigbolo)
Victor Alencar (@valencar)
Waqar Mohammad (@waqardm)
Lian Duan (@dlhandsome)
Chan Gong (@Gcaufy)
Xin Du (@clarkdo)
Alexey Pyltsyn (@lex111)
Manuel Spigolon (@eomm)
Zied CHOUK (@ZiedCHOUK)
James Youngs (@sidhuko)
Rob Simpson (@pertrai1)
Amelia Garripoli (@argoc)
Esphas Kueen (@esphas)
Antonio Gonzalez (@bluesockets)
Satyam Bansal(@satyam22)
Ankur Oberoi (@aoberoi)
Felix-Antoine Paradis (@reel)
Glenn Hinks (@ghinks)
Abdullah Tariq (@abdullahtariq91)
Mike Perry Y Attara (@mikeattara)
Kamal Singh Rawat (@ksrawat)
Dominykas Blyžė (@dominykas)
Jose Navarro (@jmn8718)
Keith Holliday (@thehollidayinn)
Ian Sutherland (@iansu)
Lars Graubner (@lgraubner)
Chandan Kumar (@chandanrjit)
Christian Kaatz (@chrkaatz)
Arne Schubert (@atd-schubert)
Ravi Joshi (@Jo-ravar)
Benjamin Chen (@BeniCheni)
Pothamsetty K (@potham)
Yash Handa (@Yash-Handa)
Ke Yang (@aojiaotage)
Tamil Vendhan Kanagarasu (@mudivili)
Gentian Elmazi (@gentios)
Kamesh Dashora (@kamesh95)
Alessio Dionisi (@adnsio)
Zeke Sikelianos (@zek)
Rick Markins (@rxmarbles)
Shailesh Kanzariya(@shailesh-kanzariya)
Hamza Baig (@hamxabaig)
Saif Eddine Jerbi (@JerbiSaif)
Edgar Muentes (@emuentes)
Karan Vohra (@kvohra3)
Tommy York (@tommyyork)
Wilbert Abreu (@wilbert-abreu)
Terary Chambers (@terary)
Konstantin Bubyakin (@Goodluckhf)
Alexander Kolesnikov (@eddort)
Anatoly Volgin (@zeroWheel)
Karan Sapolia (@karansapolia)
Andrew Kuzmenko (@andrewkuzmenko)
Zubov Kirill (@Mobydack)
Petr Grishin (@petrgrishin)
Murukesh Sadasivan (@murukesh)
Frank Lemanschik (@frank-dspeed)
Nardyuzhev Vadim (@vadinN)
James George (@jamesgeorge007)
Gabriel Schulhof (@gabrielschulhof)
Minh Nguyen (@truongminh)
Jacopo Daeli (@JacopoDaeli)
Hassan Sani (@inidaname)
Ahmad Abdul-Aziz (@devamaz)
Samuel Omole (@samie820)
Sathish Gajendran (@sathishgajendran)
Abdul Rahman Zantout (@abedzantout)
James M. Greene (@JamesMGreene)
Bethany Griggs (@BethGriggs)
Mayank Patel (@mayank-patel)
Lucas Holmquist (@lholmquist)
Darcy Clarke (@darcyclarke)
Giorgos Ntemiris (@gntem)
Helio Frota (@helio-frota)
Steven (@styfle)
Owen Buckley (@thescientist13)
Pranshu Srivastava (@rexagod)
Larson Carter (@larson-carter)
Jon Church (@jonchurch)
Antoni Kepinski (@xxczaki)
Rodion Abdurakhimov (@rodion-arr)
Ella Polo (@polec1)
Ash Cripps (@AshCripps)
Sachin Jangid (@gittysachin)
Zack Schuster (@zackschuster)

**Comment by ljharb** [comment]
I'd love to stay in the group (altho I haven't made a meeting lately, i do pay attention on github)

**Comment by mhdawson** [comment]
I'm still planning to be active

**Comment by vostrik** [comment]
I also plan to be active

**Comment by Eomm** [comment]
I plan to be active as well

**Comment by thescientist13** [comment]
Count me in!  ✌️

**Comment by pi0** [comment]
Thanks for ping @mhdawson 💚 I lost the chance to stay active in the past year but would love to start participating in discussions as well as adopt guidelines for [unjs](https://github.com/unjs) org.

**Comment by mikeattara** [comment]
I am still interested!

**Comment by reel** [comment]
Active!

**Comment by ZiedCHOUK** [comment]
I’m still interested!

**Comment by rodion-arr** [comment]
I'm still with you guys!

**Comment by clarkdo** [comment]
Thanks for letting us know this! I didn’t get chance to be active in meetings, but I’d love to stay in the group and take part in discussions more frequently.

**Comment by esphas** [comment]
Still active.

**Comment by Qard** [comment]
Not the best timing, right at the start of holidays. Might want to re-ping anyone remaining after the holidays.

**Comment by kenigbolo** [comment]
I’ve been inactive for a while but I’m definitely still interested and will be active in the coming months

**Comment by jonchurch** [comment]
Hoping 2022, and a new role at Microsoft, affords me time to participate again 👍

**Comment by Emuentes** [comment]
Haven't been as active in meetings but still following and would like to participate more in the new year. Keep me on the list if that's alright with the rest of the team.

**Comment by iansu** [comment]
I'm still interested in being involved at some level.

**Comment by ovhemert** [comment]
Also still interested in being involved.

**Comment by wesleytodd** [comment]
Sorry, sometimes work takes you in different directions and I just haven't had time to work in this area lately, but I am still sometimes pushing to `@pkgjs/nv` and I thought that might count for activity (among other reviews when I get the chance).  Either way, I am still in!

**Comment by ljharb** [comment]
To be clear, I think "activity" counts as meeting attendance, relevant discussions in slack or github, or any contributions to pkgjs projects - but this particular audit isn't about "who's active", or we wouldn't need to ask :-)

Those who are both inactive and *also* plan to remain so, it'd be great to affirmatively withdraw yourself. If one is active, I can't imagine one would ever be removed even if one misses a github notification.

**Comment by fhinkel** [comment]
I'm still interested in being involved at some level.

**Comment by zackschuster** [comment]
i still attend meetings & have work up for review in @pkgjs/create-package-json

**Comment by lholmquist** [comment]
i'm still interested.

**Comment by mhdawson** [comment]
Discussed in the meeting today. Plan is to move those who have not responded to emeritus.

**Comment by Eomm** [comment]
I can do it 👍🏽 

I saw this task has not been assigned yet in the last meeting, so I will take it

**Comment by mhdawson** [comment]
@Eomm thanks!

**Comment by craftninja** [comment]
I miss my involvement, however my plate is fairly full at the moment. Look
forward to considering becoming active again when I can. Happy new year,
friends! All the high-fives from Colorado.

Kindly,
Emily

++++++++++++++++++++++++
she/her/hers | they/them/theirs
@emilyplatzer <https://twitter.com/EmilyPlatzer>
www.emilyplatzer.com
github.com/craftninja

**Comment by Eomm** [comment]
@mhdawson doing the new member list, I noticed that, in the first post list, the latest `@usernames` do not link to the user account, so I assume they did not receive the notification.

For example, @BethGriggs is reviewing the PRs, but I did not find a reply here.

I think we should post a new message, tagging the ones that have a "dead-link".
Do you agree?

**Comment by Eomm** [comment]
Hello,
please take a look at the [first post](https://github.com/nodejs/package-maintenance/issues/499#issue-1087910597) and reply to this auditing

Arne Schubert (@atd-schubert)
Ravi Joshi (@Jo-ravar)
Benjamin Chen (@BeniCheni)
Pothamsetty K (@potham)
Yash Handa (@Yash-Handa)
Ke Yang (@aojiaotage)
Tamil Vendhan Kanagarasu (@mudivili)
Gentian Elmazi (@gentios)
Kamesh Dashora (@kamesh95)
Alessio Dionisi (@adnsio)
Zeke Sikelianos (@zek)
Rick Markins (@rxmarbles)
Shailesh Kanzariya(@shailesh-kanzariya)
Hamza Baig (@hamxabaig)
Saif Eddine Jerbi (@JerbiSaif)
Edgar Muentes (@emuentes)
Karan Vohra (@kvohra3)
Tommy York (@tommyyork)
Wilbert Abreu (@wilbert-abreu)
Terary Chambers (@terary)
Konstantin Bubyakin (@Goodluckhf)
Alexander Kolesnikov (@eddort)
Anatoly Volgin (@zeroWheel)
Karan Sapolia (@karansapolia)
Andrew Kuzmenko (@andrewkuzmenko)
Zubov Kirill (@Mobydack)
Petr Grishin (@petrgrishin)
Murukesh Sadasivan (@murukesh)
Frank Lemanschik (@frank-dspeed)
Nardyuzhev Vadim (@vadinN)
James George (@jamesgeorge007)
Gabriel Schulhof (@gabrielschulhof)
Minh Nguyen (@truongminh)
Jacopo Daeli (@JacopoDaeli)
Hassan Sani (@inidaname)
Ahmad Abdul-Aziz (@devamaz)
Samuel Omole (@samie820)
Sathish Gajendran (@sathishgajendran)
Abdul Rahman Zantout (@abedzantout)
James M. Greene (@JamesMGreene)
Bethany Griggs (@BethGriggs)
Mayank Patel (@mayank-patel)
Lucas Holmquist (@lholmquist)
Darcy Clarke (@darcyclarke)
Giorgos Ntemiris (@gntem)
Helio Frota (@helio-frota)
Steven (@styfle)
Owen Buckley (@thescientist13)
Pranshu Srivastava (@rexagod)
Larson Carter (@larson-carter)
Jon Church (@jonchurch)
Antoni Kepinski (@xxczaki)
Rodion Abdurakhimov (@rodion-arr)
Ella Polo (@polec1)
Ash Cripps (@AshCripps)
Sachin Jangid (@gittysachin)
Zack Schuster (@zackschuster)

**Comment by Eomm** [comment]
Hello,
please take a look at the [first post](https://github.com/nodejs/package-maintenance/issues/499#issue-1087910597) and reply to this auditing

Jon Church (@jonchurch)
Antoni Kepinski (@xxczaki)
Rodion Abdurakhimov (@rodion-arr)
Ella Polo (@polec1)
Ash Cripps (@AshCripps)
Sachin Jangid (@gittysachin)
Zack Schuster (@zackschuster)

**Comment by ljharb** [comment]
@poloec1

**Comment by ljharb** [comment]
@poloec1 ?

**Comment by Goodluckhf** [comment]
i'm still interested.

**Comment by gittysachin** [comment]
I'm still continuing with the community and want to be involved in activities.

**Comment by inidaname** [comment]
Hello, I will be happy if I am given the opportunity to continue with contribution to the package as I just got a new chance to use my free time for other things.

Thank you

**Comment by styfle** [comment]
> I'd love to stay in the group (altho I haven't made a meeting lately, i do pay attention on github)

Agreed.

The group itself is interesting and I was invited because of [Package Phobia](https://github.com/styfle/packagephobia/issues/308#issuecomment-792338834) but it seems like most meetings are not relevant to me. I'm more interested in the async communication then the in-person meetings.

**Comment by zek** [comment]
@zeke somehow I'm tagged instead you :) FYI

**Comment by andrewkuzmenko** [comment]
I'm still interested! 🙂

**Comment by rxmarbles** [comment]
Still planning on being involved in the group. Just getting back into the swing of things coming off paternity leave 😄

**Comment by xxczaki** [comment]
Still interested!

**Comment by zackschuster** [comment]
> Hello, please take a look at the [first post](https://github.com/nodejs/package-maintenance/issues/499#issue-1087910597) and reply to this auditing

see https://github.com/nodejs/package-maintenance/issues/499#issuecomment-1003812364

**Comment by lholmquist** [comment]
i'm still interested.

**Comment by potham** [comment]
I'm still interested

**Comment by chrkaatz** [comment]
I unfortunately cannot actively participate anymore and move to Emeritus Status. Kudos to the others who are making this happen.

**Comment by petrgrishin** [comment]
I'm still interested, thx

**Comment by SathishGajendran** [comment]
I'm still interested

Thanks

**Comment by vadinN** [comment]
I'm still interested

**Comment by zeke** [comment]
I'm fine moving to Emeritus status. 👍🏼 

Thanks for the ping, @zek 👋🏼

**Comment by karansapolia** [comment]
I'm still interested

**Comment by adnsio** [comment]
I'm fine moving to Emeritus status. Thanks for the ping

**Comment by Emuentes** [comment]
Still interested and following along.

Just need to get my new team situated before I get back into the swing of things.

I'm moving to PST timezone which may make the current meeting time easier to attend.

**Comment by truongminh** [comment]
Thank you to all those who are still actively involved! 🙇🏻‍♂️

**Comment by mayank-patel** [comment]
I'm fine moving to Emeritus status.

Thanks
Mayank

Sent from my iPhone

On Feb 4, 2022, at 5:36 PM, Alessio Dionisi ***@***.***> wrote:


I'm fine moving to Emeritus status. Thanks for the ping

**Comment by hamxabaig** [comment]
I'm still interested thanks

**Comment by MohammedEssehemy** [comment]
I'm fine to be Emeritus status. I don't expect to be active these days

**Comment by frank-dspeed** [comment]
i simply respond here now i am still activ on that topic current main activity is in rollup and typescript as also still try to figure out a gold standard for packaging and distribution.

**Comment by rexagod** [comment]
I'm fine with being moved to Emeritus status. Appreciate the ping, thanks!

**Comment by larson-carter** [comment]
Id like to stay in the active status, that way I can see progress via my GitHub notifications and I can watch recordings of meetings. Every now and then I do like to give input.

**Comment by frank-dspeed** [comment]
@DerekNonGeneric nope you did already register for the package maintance group via making a git commit in this repo this is not a new invite only a check like a ping pong to verify that all are still aktive and alive.

**Comment by zeroWheel** [comment]
I'm still interested.

**Comment by darcyclarke** [comment]
👋🏻 still interested / would like to stay active

**Comment by bnb** [comment]
I apparently missed this but still interested.

**Comment by Eomm** [comment]
I was waiting for the 4th of March (30 days), but I will start working on it earlier then 👍🏽
