### ISSUE TITLE
transfer this repo to the pkgjs org?

### ISSUE THREAD

**Issue by ljharb** [nodejs/package-maintenance#516]
Since we have a separate org, it seems strange to have this one repo live in the nodejs org.

**Comment by bnb** [comment]
My understanding is that this is an intentional decision, since teams/WGs have dedicated repos in the nodejs org. I'd prefer to keep that structure rather than having the team be completely separate from the project while still being a part of the project.

**Comment by ljharb** [comment]
Since we still can't sync github teams across orgs, this lone repo living in the node org makes management significantly more difficult :-)

**Comment by frank-dspeed** [comment]
@ljharb did you try the new github cross org projects feature? It looks pritty capable we only need to use it

**Comment by ljharb** [comment]
If I'm thinking of the right thing, i believe that requires an external SSO solution. If there's a way to do it without any external systems, i'd love a link describing it.

**Comment by frank-dspeed** [comment]
@ljharb what is the exact usecase which permissions do we need to sync i will then try to find the right solution or even implement that in github

**Comment by mhdawson** [comment]
> My understanding is that this is an intentional decision, since teams/WGs have dedicated repos in the nodejs org. I'd prefer to keep that structure rather than having the team be completely separate from the project while still being a part of the project.

**Comment by ljharb** [comment]
links would all automatically redirect, so zero work should be required, but it's fine to keep it here ¯\\\_(ツ)\_/¯

**Comment by frank-dspeed** [comment]
@ljharb in the scenario where github implements it what org would be the authoritiv one i mean that would also introduce a new permission model like corps which bundle orgs.

i wanted to suggest to keep the members here while enabling everything needed via hooks so that they check the permission level in this org and repo and then allow or refuse the action.

It should not be needed to list members in both orgs.

can you go more into detail why we need to sync the group membership with pkgjs?

**Comment by frank-dspeed** [comment]
@ljharb i am not the workforce of github thats correct but that you assume that a worker can drive github api changes makes me confused ok my english is not the best but it is well enough to understand while your specs are not well defined maybe we could implement many things that your not aware of. But ok to make it more easy for every one i will ignore your requests then we produce less noise.
