### ISSUE TITLE
move cutenode/action-import-blocklist to pkgjs

### ISSUE THREAD

**Issue by bnb** [nodejs/package-maintenance#519]
I'd like to request that we move [cutenode/action-import-blocklist](https://github.com/cutenode/action-import-blocklist) to the pkgjs org. I've written it explicitly for Node.js and syncing blocklists across our three orgs. I'm happy to keep it in cutenode if necessary, but I'd prefer to move it to a project-owned space given the approval to use it.

**Comment by mhdawson** [comment]
+1 from me

**Comment by dominykas** [comment]
👍

**Comment by bnb** [comment]
Moved the repo 👍🏻
