### ISSUE TITLE
Maybe we should form a Solution for: this Security ISSUE!

### ISSUE THREAD

**Issue by frank-dspeed** [nodejs/package-maintenance#520]
https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/

There are famous packages that pull in packages like that node-ipc one we need a solution to mass pin packages in such situations as also identify as we already do packages that depend on that. Idealy NPM would directly Tackle that what do you think?

**Comment by ljharb** [comment]
There is no sustainable solution for this kind of thing in any ecosystem.

node has an experimental “policies” feature; if you’re interested in addressing this kind of problem, that’s where you should focus efforts.

Every app should already be using a lockfile, and pinning packages any other way causes far more problems than it solves.

**Comment by frank-dspeed** [comment]
@ljharb but they do only contain most time a package-lock.json which is not designed to be deployed the shrinkwrap is the one that should get deployed and to be honest i see no where packages with a shrinkwrap

**Comment by ljharb** [comment]
Neither are designed to be deployed; the shrinkwrap file is *published*, but i very specifically said *apps*. Packages shouldn't have lockfiles at all imo, but all *apps* should - and for an app, there is NO difference whatsoever between a `package-lock.json` and an  `npm-shrinkwrap.json`. Both files are identical, and you can rename them back and forth forever with no consequence, in an app (as opposed to a published package).

**Comment by frank-dspeed** [comment]
Ok i guess thats all correct and we can do nothing about that to guard against that and it is correct in general there are enough docs around. I only had that vision that it would be enough if 1 trusted person finds code that is shared with millions deletes files that there is a way to stop that some how.

but your right thats how the ecosystem is designed may god be with us as soon as first complex cross package attacks start.

**Comment by zackschuster** [comment]
> Neither are designed to be deployed; the shrinkwrap file is _published_, but i very specifically said _apps_. Packages shouldn't have lockfiles at all imo, but all _apps_ should - and for an app, there is NO difference whatsoever between a `package-lock.json` and an `npm-shrinkwrap.json`. Both files are identical, and you can rename them back and forth forever with no consequence, in an app (as opposed to a published package).

nit: an app can use `npm-shrinkwrap.json` with an `npm pack` workflow to ensure a lockfile will end up in the `package` directory.

**Comment by frank-dspeed** [comment]
@zackschuster i understand your point but i get confuesd by the Terms: Apps, Packages, Published Packages.

Out of my view there is no diffrence in all that and there is nothing defined like a App we got published and unpublished packages that are defined. But i got the point that there should be only one authoritativ shrinkwrap in a Multi Package Project. 

but all that overlapps with overrides.

At the end i hope importMaps will clear the dust so that we get one single source of truth after taking all conditions even deep nested into consideration.

**Comment by zackschuster** [comment]
i mean "app" as in any userland program. i was thinking specifically of a server being packaged for deployment. apologies for the confusion.
