### ISSUE TITLE
Session at collaborator summit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#522]
Should we propose a session for the collaborator summit?

**Comment by thescientist13** [comment]
Maybe something from pkgjs, like the GitHub Actions matrix?

**Comment by dominykas** [comment]
I was going to open an issue to have a session about pkgjs/action, but it seems that I won't be able to make the sessions even remotely.

If someone actually submits one for the pkgjs overall (@darcyclarke? @ruyadorno?) - I'd appreciate a mention (happy to prep some ideas).

**Comment by darcyclarke** [comment]
I'm definitely open/willing to run a session at Summit (although I've missed numerous meetings as of late & not sure about the state of any WIP). I think just even submitting blank session & running an in-person meeting would be helpful (ex. we'd be able catch-up in person, plan for future WG projects/initiatives & potentially entice new ideas/folks into the WG). I can submit a generic session on behalf of the group unless @mhdawson or others had specific ideas/details in mind (also, anyone else should feel free to submit as well).

Notably, `@ruyadorno`, myself & of our `npm` team will be in attendance & could attend a Package Maintenance WG session (would also encourage everyone from this WG attend the [`npm`-specific](https://github.com/openjs-foundation/summit/issues/324) round-table/session as well).

**Comment by mhdawson** [comment]
@darcyclarke I like the idea of submitting a session which is "we'll get together and talk".  Sounds like you are willing to run the session can you go ahead and submit it.

**Comment by thescientist13** [comment]
For non-attendees, if someone could open a laptop and start an impromptu zoom, virtual attendees (like myself) could jump in on the action too!

**Comment by mhdawson** [comment]
@thescientist13 happy to do that (open laptop) once the schedule is finalized we can figure out what zoom links to use for that.

**Comment by ruyadorno** [comment]
> If someone actually submits one for the pkgjs overall (@darcyclarke? @ruyadorno?) - I'd appreciate a mention (happy to prep some ideas).

The [tentative schedule for the summit](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0) seem to be quite packed already (assuming we want to avoid concurrent sessions) if you're open to potentially run a session that conflicts with others we could propose a time, personally I would be ok with running at the end of the morning of the first day, between 10am - 12pm (I don't think the session needs to be more than an hour long though).

I'm happy to open an issue to propose that "overall" (intro + past initiatives + some light agenda) session if we can agree on what's the best timing to run it.
