### ISSUE TITLE
Goals for 2023

### ISSUE THREAD

**Issue by mhdawson** [nodejs/package-maintenance#550]
Lets start the year by talking about goals for the new year for the package maintenance team

Please add your thoughts/suggestions over the next few weeks until the next meeting.

**Comment by ljharb** [comment]
I'd like to see us get one of our solutions to the point where it's easily mass-adoptable.

**Comment by lholmquist** [comment]
I know this is a "hot" subject,  but it would be interesting if we could have some sort of solution for dual CJS/ESM .  wether that is just a doc/blog post or some sort of tool

**Comment by ljharb** [comment]
@lholmquist what kind of solution is needed? "just CJS" already works in every module system.

**Comment by lholmquist** [comment]
> what kind of solution is needed? "just CJS" already works in every module system.

I guess i'm thinking more for those people who want to start writing their packages as ES modules, but also want to make sure they aren't breaking other people who are using it and have a smoother(?) transition.

**Comment by ljharb** [comment]
That's the problem - there isn't a universal way to make sure of that except to author in ESM and transpile to CJS. If you ship any native ESM, it takes an inordinate amount of work to make sure everyone can still use your package.

**Comment by darcyclarke** [comment]
Had a great chat today with @mhdawson @rxmarbles @ruyadorno - wasn't streamed unfortunately.

### Suggested Projects to Tackle in 2023
- [ ] move `package.json` documentation into it's own page (not nested/hidden in other docs pages) & formalize any missing fields/context that would be helpful
- [ ] document common package fields & values to set for new projects (stretch goal is to document best practices around ESM+CJS)
- [ ] complete work on `@pkgjs/create` to scaffold & validate those documented common fields (with the hopes other tools/package managers will adopt it as the default `init` module/functionality)
- [ ] create a new "statusboard" - similar to npm's [projects statusboard](https://npm.github.io/statusboard/) - to track the state of # number of "popular"/"impactful" packages (notably, we can leverage the existing known set of "top" (ex. https://gist.github.com/anvaka/8e8fa57c7ee1350e3491) - ref. to [existing project](https://github.com/pkgjs/statusboard) that needs some love

**Comment by mhdawson** [comment]
@bensternthal, the fourth one on the list above `Launch Impactful Packages statusboard` sounds like it aligns/has some commonality with some of the work you outlined being done under the Sovereign tech fund effort.  

Maybe if you expanded a bit on what you were planning on that front we can confirm if the two efforts might align?

**Comment by wesleytodd** [comment]
I am trying to plug myself back in here (actually got to inbox 0 on notifications to help!!!) and so I was wondering two things:

1. the first two of these seem to overlap with the ideas of documenting and maybe standardizing some `package.json` things. Do you see theses as separate?
2. The create stuff, I have some of the foundations laid for this, what are next steps? Is this on a meeting agenda I can attend to discuss? I did a deep dive on the approach for `create-package-json` once with a few folks, and there is a technical design in a repo somewhere. Would it be helpful to refresh on that?

**Comment by mhdawson** [comment]
We have issues/volunteers to cover the suggested goals so going to close this:

These would be the issues covering the goals:
https://github.com/nodejs/package-maintenance/issues/569
https://github.com/nodejs/package-maintenance/issues/542
https://github.com/nodejs/package-maintenance/issues/458
https://github.com/openjs-foundation/package-json-research/issues/1
