### ISSUE TITLE
Suggestion: Job Board for common maintenance tasks

### ISSUE THREAD

**Issue by balupton** [nodejs/package-maintenance#59]
As an alternative to wikis and tooling to solve maintenance issues, for things that require manual efforts, such as:

- converting a project to typescript
- writing typescript declaration files
- upgrading dependency that has breaking changes across all dependents of it

It would be nice to have a job board, so that say someone in a specialist of upgrading X dependency can do it at $50 a pop for all dependents. Or someone who is an expert in typescript can convert the most used projects to typescripts or do up their declaration files for $50 a pop.

I'd certainly be a employer and employee of this service. It will also help provide jobs for the maintainers by trade, as well as help them work on the most scarce work of their talent while delegating common lesser gruels to others.

---

For instance, I've spent 3 weeks trying to learn typescript and convert all of @bevry's utility libraries to typescript, or at least provide declaration files for them. This is large waste of time for me, for the benefits of others, as it detracts from the product work I should be doing to earn an income. I'd much rather get a job for 3 weeks as an expert consultant, and pay a TypeScript expert $500 to convert everything (a few days work of consultancy for me), than for me spending 3+ weeks unpaid wrestling with learning and implementing typescript. However now that I am somewhat familiar with typescript, perhaps I can convert other libraries for a fee, as a way to recoup my efforts.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mcollina** [comment]
I quite like this proposal. However it's quite unclear to me:

a) how payment will be handled, how the money is being managed
b) how it is different from other services that offer rewards for bugs fixed
c) how you consider a task "done"
d) who can post on the job board

**Comment by balupton** [comment]
<details>
@bnb no thank you, especially without any reason, regardless here is my reason: The contrast it provides is apt for what I wished to communicate, that open-source is often slavery to servitude, I wouldn't have used it if I didn't think it was fitting. It is what open source feels like, and often manifests itself as, at least in my case: unpaid labour due to an obligation to serve people who make their demands on me, endlessly, without resolve, without rest — naturally, it isn't slavery by whip, or gun, or race, hence my exact phrasing. I am not sure what fueled your request, whether or not it was desire to protect the offended, which is what #67 seems to imply, if that is the case, perhaps considering what the speaker means by a phrase would be more valuable than considering ways people could misapply it to offend themselves. I can redact the whole sentiment under a trigger warning details element if you think that will suffice, but censorsing an apt sentiment I don't think is honourable, nor compassionate. Happy to follow this up over email b@lupton.cc or on #67 as perhaps I'm missing something, and I don't want to argue this in this thread as it would change the topic of this thread — a discussion about a maintenance job board proposal (with the OP including why I think it is important, as a way from moving from slavery to servitude to a mutually rewarding trade exchange), rather than a dicussion about the language used.
</details>

**Comment by abdullahtariq91** [comment]
We can probably take some inspiration from [24pullrequests](https://24pullrequests.com/) on this one.

**Comment by mcollina** [comment]
cc @andrew (the author of 24pullrequests), maybe he can help and be part of the discussion!

**Comment by Eomm** [comment]
is this the same service implemented by [issuehunt](https://issuehunt.io/)?

**Comment by jonchurch** [comment]
I'm closing this as out of scope for the project at this time. Can always be reopened if others have more to add.
